/*
 * generated by Xtext 2.38.0
 */
package com.yunzhi.parser.antlr;

import com.google.inject.Inject;
import com.yunzhi.parser.antlr.internal.InternalGenoMateParser;
import com.yunzhi.services.GenoMateGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GenoMateParser extends AbstractAntlrParser {

	@Inject
	private GenoMateGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGenoMateParser createParser(XtextTokenStream stream) {
		return new InternalGenoMateParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GenoMate";
	}

	public GenoMateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GenoMateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
