/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(GenoMateInjectorProvider.class)
@SuppressWarnings("all")
public class GenoMateParsingTest {
  @Inject
  private /* ParseHelper<ModelGenerator> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field GenoMateParsingTest.parseHelper refers to the missing type ModelGenerator"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
