/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Type Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.AndTypeCondition#getLeft <em>Left</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.AndTypeCondition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getAndTypeCondition()
 * @model
 * @generated
 */
public interface AndTypeCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(TypeEqualityCondition)
   * @see com.yunzhi.genoMate.GenoMatePackage#getAndTypeCondition_Left()
   * @model containment="true"
   * @generated
   */
  TypeEqualityCondition getLeft();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.AndTypeCondition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(TypeEqualityCondition value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.TypeEqualityCondition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getAndTypeCondition_Right()
   * @model containment="true"
   * @generated
   */
  EList<TypeEqualityCondition> getRight();

} // AndTypeCondition
