/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation Parameters</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.AnnotationParameters#getAnnparameters <em>Annparameters</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.AnnotationParameters#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getAnnotationParameters()
 * @model
 * @generated
 */
public interface AnnotationParameters extends EObject
{
  /**
   * Returns the value of the '<em><b>Annparameters</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annparameters</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getAnnotationParameters_Annparameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getAnnparameters();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getAnnotationParameters_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // AnnotationParameters
