/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dto Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getName <em>Name</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getSerializable <em>Serializable</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getLombokAnnotation <em>Lombok Annotation</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getExclusions <em>Exclusions</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getExcludeAll <em>Exclude All</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getFieldAnnotationsBlock <em>Field Annotations Block</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DtoDefinition#getAddField <em>Add Field</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition()
 * @model
 * @generated
 */
public interface DtoDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DtoDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Serializable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Serializable</em>' attribute.
   * @see #setSerializable(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_Serializable()
   * @model
   * @generated
   */
  String getSerializable();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DtoDefinition#getSerializable <em>Serializable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Serializable</em>' attribute.
   * @see #getSerializable()
   * @generated
   */
  void setSerializable(String value);

  /**
   * Returns the value of the '<em><b>Lombok Annotation</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.LombokAnnotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lombok Annotation</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_LombokAnnotation()
   * @model containment="true"
   * @generated
   */
  EList<LombokAnnotation> getLombokAnnotation();

  /**
   * Returns the value of the '<em><b>Exclusions</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.Exclusions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusions</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_Exclusions()
   * @model containment="true"
   * @generated
   */
  EList<Exclusions> getExclusions();

  /**
   * Returns the value of the '<em><b>Exclude All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclude All</em>' attribute.
   * @see #setExcludeAll(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_ExcludeAll()
   * @model
   * @generated
   */
  String getExcludeAll();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DtoDefinition#getExcludeAll <em>Exclude All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclude All</em>' attribute.
   * @see #getExcludeAll()
   * @generated
   */
  void setExcludeAll(String value);

  /**
   * Returns the value of the '<em><b>Field Annotations Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Annotations Block</em>' containment reference.
   * @see #setFieldAnnotationsBlock(FieldValidationBlock)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_FieldAnnotationsBlock()
   * @model containment="true"
   * @generated
   */
  FieldValidationBlock getFieldAnnotationsBlock();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DtoDefinition#getFieldAnnotationsBlock <em>Field Annotations Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Annotations Block</em>' containment reference.
   * @see #getFieldAnnotationsBlock()
   * @generated
   */
  void setFieldAnnotationsBlock(FieldValidationBlock value);

  /**
   * Returns the value of the '<em><b>Add Field</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.DtoAddField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Field</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoDefinition_AddField()
   * @model containment="true"
   * @generated
   */
  EList<DtoAddField> getAddField();

} // DtoDefinition
