/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dto Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.DtoRule#getDtos <em>Dtos</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getDtoRule()
 * @model
 * @generated
 */
public interface DtoRule extends GenerationRule
{
  /**
   * Returns the value of the '<em><b>Dtos</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.DtoDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dtos</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getDtoRule_Dtos()
   * @model containment="true"
   * @generated
   */
  EList<DtoDefinition> getDtos();

} // DtoRule
