/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DTO To Model Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.DTOToModelMapping#getSource <em>Source</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.DTOToModelMapping#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getDTOToModelMapping()
 * @model
 * @generated
 */
public interface DTOToModelMapping extends Mapping
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(DtoDefinition)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDTOToModelMapping_Source()
   * @model
   * @generated
   */
  DtoDefinition getSource();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DTOToModelMapping#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(DtoDefinition value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Model)
   * @see com.yunzhi.genoMate.GenoMatePackage#getDTOToModelMapping_Target()
   * @model
   * @generated
   */
  Model getTarget();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.DTOToModelMapping#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Model value);

} // DTOToModelMapping
