/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generic Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.GenericDataType#getContainerTypeName <em>Container Type Name</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.GenericDataType#getContainedTypeName <em>Contained Type Name</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getGenericDataType()
 * @model
 * @generated
 */
public interface GenericDataType extends Type
{
  /**
   * Returns the value of the '<em><b>Container Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Type Name</em>' attribute.
   * @see #setContainerTypeName(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenericDataType_ContainerTypeName()
   * @model
   * @generated
   */
  String getContainerTypeName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GenericDataType#getContainerTypeName <em>Container Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Type Name</em>' attribute.
   * @see #getContainerTypeName()
   * @generated
   */
  void setContainerTypeName(String value);

  /**
   * Returns the value of the '<em><b>Contained Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contained Type Name</em>' containment reference.
   * @see #setContainedTypeName(Type)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenericDataType_ContainedTypeName()
   * @model containment="true"
   * @generated
   */
  Type getContainedTypeName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GenericDataType#getContainedTypeName <em>Contained Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contained Type Name</em>' containment reference.
   * @see #getContainedTypeName()
   * @generated
   */
  void setContainedTypeName(Type value);

} // GenericDataType
