/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Geno Mate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.GenoMate#getGlobalConfig <em>Global Config</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.GenoMate#getModel <em>Model</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.GenoMate#getGenerateSection <em>Generate Section</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.GenoMate#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getGenoMate()
 * @model
 * @generated
 */
public interface GenoMate extends EObject
{
  /**
   * Returns the value of the '<em><b>Global Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Config</em>' containment reference.
   * @see #setGlobalConfig(GlobalConfig)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenoMate_GlobalConfig()
   * @model containment="true"
   * @generated
   */
  GlobalConfig getGlobalConfig();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GenoMate#getGlobalConfig <em>Global Config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Config</em>' containment reference.
   * @see #getGlobalConfig()
   * @generated
   */
  void setGlobalConfig(GlobalConfig value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(Model)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenoMate_Model()
   * @model containment="true"
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GenoMate#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

  /**
   * Returns the value of the '<em><b>Generate Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generate Section</em>' containment reference.
   * @see #setGenerateSection(GenerateSection)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenoMate_GenerateSection()
   * @model containment="true"
   * @generated
   */
  GenerateSection getGenerateSection();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GenoMate#getGenerateSection <em>Generate Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generate Section</em>' containment reference.
   * @see #getGenerateSection()
   * @generated
   */
  void setGenerateSection(GenerateSection value);

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.Mapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getGenoMate_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<Mapping> getMappings();

} // GenoMate
