/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.GlobalConfig#getPackage <em>Package</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.GlobalConfig#getVarDefaultAnnotations <em>Var Default Annotations</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getGlobalConfig()
 * @model
 * @generated
 */
public interface GlobalConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' attribute.
   * @see #setPackage(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getGlobalConfig_Package()
   * @model
   * @generated
   */
  String getPackage();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.GlobalConfig#getPackage <em>Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' attribute.
   * @see #getPackage()
   * @generated
   */
  void setPackage(String value);

  /**
   * Returns the value of the '<em><b>Var Default Annotations</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.VariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Default Annotations</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getGlobalConfig_VarDefaultAnnotations()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclaration> getVarDefaultAnnotations();

} // GlobalConfig
