/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Jackson Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.yunzhi.genoMate.GenoMatePackage#getJacksonType()
 * @model
 * @generated
 */
public enum JacksonType implements Enumerator
{
  /**
   * The '<em><b>Json Alias</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ALIAS_VALUE
   * @generated
   * @ordered
   */
  JSON_ALIAS(0, "JsonAlias", "JsonAlias"),

  /**
   * The '<em><b>Json Any Getter</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ANY_GETTER_VALUE
   * @generated
   * @ordered
   */
  JSON_ANY_GETTER(1, "JsonAnyGetter", "JsonAnyGetter"),

  /**
   * The '<em><b>Json Any Setter</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ANY_SETTER_VALUE
   * @generated
   * @ordered
   */
  JSON_ANY_SETTER(2, "JsonAnySetter", "JsonAnySetter"),

  /**
   * The '<em><b>Json Auto Detect</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_AUTO_DETECT_VALUE
   * @generated
   * @ordered
   */
  JSON_AUTO_DETECT(3, "JsonAutoDetect", "JsonAutoDetect"),

  /**
   * The '<em><b>Json Deserialize</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_DESERIALIZE_VALUE
   * @generated
   * @ordered
   */
  JSON_DESERIALIZE(4, "JsonDeserialize", "JsonDeserialize"),

  /**
   * The '<em><b>Json Format</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_FORMAT_VALUE
   * @generated
   * @ordered
   */
  JSON_FORMAT(5, "JsonFormat", "JsonFormat"),

  /**
   * The '<em><b>Json Ignore</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_IGNORE_VALUE
   * @generated
   * @ordered
   */
  JSON_IGNORE(6, "JsonIgnore", "JsonIgnore"),

  /**
   * The '<em><b>Json Ignore Properties</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_IGNORE_PROPERTIES_VALUE
   * @generated
   * @ordered
   */
  JSON_IGNORE_PROPERTIES(7, "JsonIgnoreProperties", "JsonIgnoreProperties"),

  /**
   * The '<em><b>Json Include</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_INCLUDE_VALUE
   * @generated
   * @ordered
   */
  JSON_INCLUDE(8, "JsonInclude", "JsonInclude"),

  /**
   * The '<em><b>Json Root Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ROOT_NAME_VALUE
   * @generated
   * @ordered
   */
  JSON_ROOT_NAME(9, "JsonRootName", "JsonRootName"),

  /**
   * The '<em><b>Json Serialize</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_SERIALIZE_VALUE
   * @generated
   * @ordered
   */
  JSON_SERIALIZE(10, "JsonSerialize", "JsonSerialize"),

  /**
   * The '<em><b>Json Type Info</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_TYPE_INFO_VALUE
   * @generated
   * @ordered
   */
  JSON_TYPE_INFO(11, "JsonTypeInfo", "JsonTypeInfo"),

  /**
   * The '<em><b>Json Unwrapped</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_UNWRAPPED_VALUE
   * @generated
   * @ordered
   */
  JSON_UNWRAPPED(12, "JsonUnwrapped", "JsonUnwrapped"),

  /**
   * The '<em><b>Json Value</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_VALUE_VALUE
   * @generated
   * @ordered
   */
  JSON_VALUE(13, "JsonValue", "JsonValue"),

  /**
   * The '<em><b>Json View</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_VIEW_VALUE
   * @generated
   * @ordered
   */
  JSON_VIEW(14, "JsonView", "JsonView"),

  /**
   * The '<em><b>Json Property</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_PROPERTY_VALUE
   * @generated
   * @ordered
   */
  JSON_PROPERTY(15, "JsonProperty", "JsonProperty");

  /**
   * The '<em><b>Json Alias</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ALIAS
   * @model name="JsonAlias"
   * @generated
   * @ordered
   */
  public static final int JSON_ALIAS_VALUE = 0;

  /**
   * The '<em><b>Json Any Getter</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ANY_GETTER
   * @model name="JsonAnyGetter"
   * @generated
   * @ordered
   */
  public static final int JSON_ANY_GETTER_VALUE = 1;

  /**
   * The '<em><b>Json Any Setter</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ANY_SETTER
   * @model name="JsonAnySetter"
   * @generated
   * @ordered
   */
  public static final int JSON_ANY_SETTER_VALUE = 2;

  /**
   * The '<em><b>Json Auto Detect</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_AUTO_DETECT
   * @model name="JsonAutoDetect"
   * @generated
   * @ordered
   */
  public static final int JSON_AUTO_DETECT_VALUE = 3;

  /**
   * The '<em><b>Json Deserialize</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_DESERIALIZE
   * @model name="JsonDeserialize"
   * @generated
   * @ordered
   */
  public static final int JSON_DESERIALIZE_VALUE = 4;

  /**
   * The '<em><b>Json Format</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_FORMAT
   * @model name="JsonFormat"
   * @generated
   * @ordered
   */
  public static final int JSON_FORMAT_VALUE = 5;

  /**
   * The '<em><b>Json Ignore</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_IGNORE
   * @model name="JsonIgnore"
   * @generated
   * @ordered
   */
  public static final int JSON_IGNORE_VALUE = 6;

  /**
   * The '<em><b>Json Ignore Properties</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_IGNORE_PROPERTIES
   * @model name="JsonIgnoreProperties"
   * @generated
   * @ordered
   */
  public static final int JSON_IGNORE_PROPERTIES_VALUE = 7;

  /**
   * The '<em><b>Json Include</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_INCLUDE
   * @model name="JsonInclude"
   * @generated
   * @ordered
   */
  public static final int JSON_INCLUDE_VALUE = 8;

  /**
   * The '<em><b>Json Root Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_ROOT_NAME
   * @model name="JsonRootName"
   * @generated
   * @ordered
   */
  public static final int JSON_ROOT_NAME_VALUE = 9;

  /**
   * The '<em><b>Json Serialize</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_SERIALIZE
   * @model name="JsonSerialize"
   * @generated
   * @ordered
   */
  public static final int JSON_SERIALIZE_VALUE = 10;

  /**
   * The '<em><b>Json Type Info</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_TYPE_INFO
   * @model name="JsonTypeInfo"
   * @generated
   * @ordered
   */
  public static final int JSON_TYPE_INFO_VALUE = 11;

  /**
   * The '<em><b>Json Unwrapped</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_UNWRAPPED
   * @model name="JsonUnwrapped"
   * @generated
   * @ordered
   */
  public static final int JSON_UNWRAPPED_VALUE = 12;

  /**
   * The '<em><b>Json Value</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_VALUE
   * @model name="JsonValue"
   * @generated
   * @ordered
   */
  public static final int JSON_VALUE_VALUE = 13;

  /**
   * The '<em><b>Json View</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_VIEW
   * @model name="JsonView"
   * @generated
   * @ordered
   */
  public static final int JSON_VIEW_VALUE = 14;

  /**
   * The '<em><b>Json Property</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JSON_PROPERTY
   * @model name="JsonProperty"
   * @generated
   * @ordered
   */
  public static final int JSON_PROPERTY_VALUE = 15;

  /**
   * An array of all the '<em><b>Jackson Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final JacksonType[] VALUES_ARRAY =
    new JacksonType[]
    {
      JSON_ALIAS,
      JSON_ANY_GETTER,
      JSON_ANY_SETTER,
      JSON_AUTO_DETECT,
      JSON_DESERIALIZE,
      JSON_FORMAT,
      JSON_IGNORE,
      JSON_IGNORE_PROPERTIES,
      JSON_INCLUDE,
      JSON_ROOT_NAME,
      JSON_SERIALIZE,
      JSON_TYPE_INFO,
      JSON_UNWRAPPED,
      JSON_VALUE,
      JSON_VIEW,
      JSON_PROPERTY,
    };

  /**
   * A public read-only list of all the '<em><b>Jackson Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<JacksonType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Jackson Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static JacksonType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      JacksonType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Jackson Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static JacksonType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      JacksonType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Jackson Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static JacksonType get(int value)
  {
    switch (value)
    {
      case JSON_ALIAS_VALUE: return JSON_ALIAS;
      case JSON_ANY_GETTER_VALUE: return JSON_ANY_GETTER;
      case JSON_ANY_SETTER_VALUE: return JSON_ANY_SETTER;
      case JSON_AUTO_DETECT_VALUE: return JSON_AUTO_DETECT;
      case JSON_DESERIALIZE_VALUE: return JSON_DESERIALIZE;
      case JSON_FORMAT_VALUE: return JSON_FORMAT;
      case JSON_IGNORE_VALUE: return JSON_IGNORE;
      case JSON_IGNORE_PROPERTIES_VALUE: return JSON_IGNORE_PROPERTIES;
      case JSON_INCLUDE_VALUE: return JSON_INCLUDE;
      case JSON_ROOT_NAME_VALUE: return JSON_ROOT_NAME;
      case JSON_SERIALIZE_VALUE: return JSON_SERIALIZE;
      case JSON_TYPE_INFO_VALUE: return JSON_TYPE_INFO;
      case JSON_UNWRAPPED_VALUE: return JSON_UNWRAPPED;
      case JSON_VALUE_VALUE: return JSON_VALUE;
      case JSON_VIEW_VALUE: return JSON_VIEW;
      case JSON_PROPERTY_VALUE: return JSON_PROPERTY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private JacksonType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //JacksonType
