/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Loop Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.LocalLoopAction#getVarDeclarations <em>Var Declarations</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.LocalLoopAction#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getLocalLoopAction()
 * @model
 * @generated
 */
public interface LocalLoopAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Declarations</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.VariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Declarations</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getLocalLoopAction_VarDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclaration> getVarDeclarations();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.LocalAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getLocalLoopAction_Actions()
   * @model containment="true"
   * @generated
   */
  EList<LocalAction> getActions();

} // LocalLoopAction
