/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.MappingRule#getTargetField <em>Target Field</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.MappingRule#getSourceField <em>Source Field</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.MappingRule#getDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getMappingRule()
 * @model
 * @generated
 */
public interface MappingRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Field</em>' reference.
   * @see #setTargetField(Field)
   * @see com.yunzhi.genoMate.GenoMatePackage#getMappingRule_TargetField()
   * @model
   * @generated
   */
  Field getTargetField();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.MappingRule#getTargetField <em>Target Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Field</em>' reference.
   * @see #getTargetField()
   * @generated
   */
  void setTargetField(Field value);

  /**
   * Returns the value of the '<em><b>Source Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Field</em>' reference.
   * @see #setSourceField(Field)
   * @see com.yunzhi.genoMate.GenoMatePackage#getMappingRule_SourceField()
   * @model
   * @generated
   */
  Field getSourceField();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.MappingRule#getSourceField <em>Source Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Field</em>' reference.
   * @see #getSourceField()
   * @generated
   */
  void setSourceField(Field value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getMappingRule_Default()
   * @model
   * @generated
   */
  String getDefault();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.MappingRule#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(String value);

} // MappingRule
