/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model To VO Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.ModelToVOMapping#getSource <em>Source</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.ModelToVOMapping#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getModelToVOMapping()
 * @model
 * @generated
 */
public interface ModelToVOMapping extends Mapping
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Model)
   * @see com.yunzhi.genoMate.GenoMatePackage#getModelToVOMapping_Source()
   * @model
   * @generated
   */
  Model getSource();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.ModelToVOMapping#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Model value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(VoDefinition)
   * @see com.yunzhi.genoMate.GenoMatePackage#getModelToVOMapping_Target()
   * @model
   * @generated
   */
  VoDefinition getTarget();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.ModelToVOMapping#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(VoDefinition value);

} // ModelToVOMapping
