/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Mybatis Plus Field Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.yunzhi.genoMate.GenoMatePackage#getMybatisPlusFieldType()
 * @model
 * @generated
 */
public enum MybatisPlusFieldType implements Enumerator
{
  /**
   * The '<em><b>Order By</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORDER_BY_VALUE
   * @generated
   * @ordered
   */
  ORDER_BY(0, "OrderBy", "OrderBy"),

  /**
   * The '<em><b>Table Field</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_FIELD_VALUE
   * @generated
   * @ordered
   */
  TABLE_FIELD(1, "TableField", "TableField"),

  /**
   * The '<em><b>Table Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_ID_VALUE
   * @generated
   * @ordered
   */
  TABLE_ID(2, "TableId", "TableId"),

  /**
   * The '<em><b>Table Logic</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_LOGIC_VALUE
   * @generated
   * @ordered
   */
  TABLE_LOGIC(3, "TableLogic", "TableLogic"),

  /**
   * The '<em><b>Version</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VERSION_VALUE
   * @generated
   * @ordered
   */
  VERSION(4, "Version", "Version");

  /**
   * The '<em><b>Order By</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORDER_BY
   * @model name="OrderBy"
   * @generated
   * @ordered
   */
  public static final int ORDER_BY_VALUE = 0;

  /**
   * The '<em><b>Table Field</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_FIELD
   * @model name="TableField"
   * @generated
   * @ordered
   */
  public static final int TABLE_FIELD_VALUE = 1;

  /**
   * The '<em><b>Table Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_ID
   * @model name="TableId"
   * @generated
   * @ordered
   */
  public static final int TABLE_ID_VALUE = 2;

  /**
   * The '<em><b>Table Logic</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_LOGIC
   * @model name="TableLogic"
   * @generated
   * @ordered
   */
  public static final int TABLE_LOGIC_VALUE = 3;

  /**
   * The '<em><b>Version</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VERSION
   * @model name="Version"
   * @generated
   * @ordered
   */
  public static final int VERSION_VALUE = 4;

  /**
   * An array of all the '<em><b>Mybatis Plus Field Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final MybatisPlusFieldType[] VALUES_ARRAY =
    new MybatisPlusFieldType[]
    {
      ORDER_BY,
      TABLE_FIELD,
      TABLE_ID,
      TABLE_LOGIC,
      VERSION,
    };

  /**
   * A public read-only list of all the '<em><b>Mybatis Plus Field Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<MybatisPlusFieldType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Mybatis Plus Field Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusFieldType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MybatisPlusFieldType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mybatis Plus Field Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusFieldType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MybatisPlusFieldType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mybatis Plus Field Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusFieldType get(int value)
  {
    switch (value)
    {
      case ORDER_BY_VALUE: return ORDER_BY;
      case TABLE_FIELD_VALUE: return TABLE_FIELD;
      case TABLE_ID_VALUE: return TABLE_ID;
      case TABLE_LOGIC_VALUE: return TABLE_LOGIC;
      case VERSION_VALUE: return VERSION;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private MybatisPlusFieldType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //MybatisPlusFieldType
