/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Mybatis Plus Model Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.yunzhi.genoMate.GenoMatePackage#getMybatisPlusModelType()
 * @model
 * @generated
 */
public enum MybatisPlusModelType implements Enumerator
{
  /**
   * The '<em><b>Key Sequence</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KEY_SEQUENCE_VALUE
   * @generated
   * @ordered
   */
  KEY_SEQUENCE(0, "KeySequence", "KeySequence"),

  /**
   * The '<em><b>Table Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_NAME_VALUE
   * @generated
   * @ordered
   */
  TABLE_NAME(1, "TableName", "TableName");

  /**
   * The '<em><b>Key Sequence</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KEY_SEQUENCE
   * @model name="KeySequence"
   * @generated
   * @ordered
   */
  public static final int KEY_SEQUENCE_VALUE = 0;

  /**
   * The '<em><b>Table Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TABLE_NAME
   * @model name="TableName"
   * @generated
   * @ordered
   */
  public static final int TABLE_NAME_VALUE = 1;

  /**
   * An array of all the '<em><b>Mybatis Plus Model Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final MybatisPlusModelType[] VALUES_ARRAY =
    new MybatisPlusModelType[]
    {
      KEY_SEQUENCE,
      TABLE_NAME,
    };

  /**
   * A public read-only list of all the '<em><b>Mybatis Plus Model Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<MybatisPlusModelType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Mybatis Plus Model Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusModelType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MybatisPlusModelType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mybatis Plus Model Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusModelType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MybatisPlusModelType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mybatis Plus Model Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MybatisPlusModelType get(int value)
  {
    switch (value)
    {
      case KEY_SEQUENCE_VALUE: return KEY_SEQUENCE;
      case TABLE_NAME_VALUE: return TABLE_NAME;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private MybatisPlusModelType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //MybatisPlusModelType
