/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mybatis Plus Model Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.MybatisPlusModelAnnotation#getName <em>Name</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.MybatisPlusModelAnnotation#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getMybatisPlusModelAnnotation()
 * @model
 * @generated
 */
public interface MybatisPlusModelAnnotation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link com.yunzhi.genoMate.MybatisPlusModelType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see com.yunzhi.genoMate.MybatisPlusModelType
   * @see #setName(MybatisPlusModelType)
   * @see com.yunzhi.genoMate.GenoMatePackage#getMybatisPlusModelAnnotation_Name()
   * @model
   * @generated
   */
  MybatisPlusModelType getName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.MybatisPlusModelAnnotation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see com.yunzhi.genoMate.MybatisPlusModelType
   * @see #getName()
   * @generated
   */
  void setName(MybatisPlusModelType value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(AnnotationParameters)
   * @see com.yunzhi.genoMate.GenoMatePackage#getMybatisPlusModelAnnotation_Parameters()
   * @model containment="true"
   * @generated
   */
  AnnotationParameters getParameters();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.MybatisPlusModelAnnotation#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(AnnotationParameters value);

} // MybatisPlusModelAnnotation
