/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.NormalType#getCustomType <em>Custom Type</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getNormalType()
 * @model
 * @generated
 */
public interface NormalType extends Type
{
  /**
   * Returns the value of the '<em><b>Custom Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Type</em>' attribute.
   * @see #setCustomType(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getNormalType_CustomType()
   * @model
   * @generated
   */
  String getCustomType();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.NormalType#getCustomType <em>Custom Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Type</em>' attribute.
   * @see #getCustomType()
   * @generated
   */
  void setCustomType(String value);

} // NormalType
