/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or Type Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.OrTypeCondition#getLeft <em>Left</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.OrTypeCondition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getOrTypeCondition()
 * @model
 * @generated
 */
public interface OrTypeCondition extends TypeCondition
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(AndTypeCondition)
   * @see com.yunzhi.genoMate.GenoMatePackage#getOrTypeCondition_Left()
   * @model containment="true"
   * @generated
   */
  AndTypeCondition getLeft();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.OrTypeCondition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(AndTypeCondition value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.AndTypeCondition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getOrTypeCondition_Right()
   * @model containment="true"
   * @generated
   */
  EList<AndTypeCondition> getRight();

} // OrTypeCondition
