/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.PropertyDeclaration#getStatic <em>Static</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.PropertyDeclaration#getFinal <em>Final</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.PropertyDeclaration#getType <em>Type</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.PropertyDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.PropertyDeclaration#getDefaultClause <em>Default Clause</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration()
 * @model
 * @generated
 */
public interface PropertyDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static</em>' attribute.
   * @see #setStatic(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration_Static()
   * @model
   * @generated
   */
  String getStatic();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.PropertyDeclaration#getStatic <em>Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Static</em>' attribute.
   * @see #getStatic()
   * @generated
   */
  void setStatic(String value);

  /**
   * Returns the value of the '<em><b>Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final</em>' attribute.
   * @see #setFinal(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration_Final()
   * @model
   * @generated
   */
  String getFinal();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.PropertyDeclaration#getFinal <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Final</em>' attribute.
   * @see #getFinal()
   * @generated
   */
  void setFinal(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.PropertyDeclaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.PropertyDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Default Clause</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Clause</em>' attribute.
   * @see #setDefaultClause(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getPropertyDeclaration_DefaultClause()
   * @model
   * @generated
   */
  String getDefaultClause();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.PropertyDeclaration#getDefaultClause <em>Default Clause</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Clause</em>' attribute.
   * @see #getDefaultClause()
   * @generated
   */
  void setDefaultClause(String value);

} // PropertyDeclaration
