/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.SimpleType#getBuiltInType <em>Built In Type</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getSimpleType()
 * @model
 * @generated
 */
public interface SimpleType extends Type
{
  /**
   * Returns the value of the '<em><b>Built In Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.yunzhi.genoMate.BuiltInType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Built In Type</em>' attribute.
   * @see com.yunzhi.genoMate.BuiltInType
   * @see #setBuiltInType(BuiltInType)
   * @see com.yunzhi.genoMate.GenoMatePackage#getSimpleType_BuiltInType()
   * @model
   * @generated
   */
  BuiltInType getBuiltInType();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.SimpleType#getBuiltInType <em>Built In Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Built In Type</em>' attribute.
   * @see com.yunzhi.genoMate.BuiltInType
   * @see #getBuiltInType()
   * @generated
   */
  void setBuiltInType(BuiltInType value);

} // SimpleType
