/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.SingleAction#getValidations <em>Validations</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getSingleAction()
 * @model
 * @generated
 */
public interface SingleAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Validations</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.DtoValidation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validations</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getSingleAction_Validations()
   * @model containment="true"
   * @generated
   */
  EList<DtoValidation> getValidations();

} // SingleAction
