/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getTypeCondition()
 * @model
 * @generated
 */
public interface TypeCondition extends EObject
{
} // TypeCondition
