/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vo Add Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.VoAddField#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoAddField#getAnnotationList <em>Annotation List</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getVoAddField()
 * @model
 * @generated
 */
public interface VoAddField extends EObject
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference.
   * @see #setProperties(PropertyDeclaration)
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoAddField_Properties()
   * @model containment="true"
   * @generated
   */
  PropertyDeclaration getProperties();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.VoAddField#getProperties <em>Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Properties</em>' containment reference.
   * @see #getProperties()
   * @generated
   */
  void setProperties(PropertyDeclaration value);

  /**
   * Returns the value of the '<em><b>Annotation List</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.JacksonAnnotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotation List</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoAddField_AnnotationList()
   * @model containment="true"
   * @generated
   */
  EList<JacksonAnnotation> getAnnotationList();

} // VoAddField
