/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vo Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getName <em>Name</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getSerializable <em>Serializable</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getLombokAnnotation <em>Lombok Annotation</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getExclusions <em>Exclusions</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getExcludeAll <em>Exclude All</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getJacksons <em>Jacksons</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.VoDefinition#getAddField <em>Add Field</em>}</li>
 * </ul>
 *
 * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition()
 * @model
 * @generated
 */
public interface VoDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.VoDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Serializable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Serializable</em>' attribute.
   * @see #setSerializable(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_Serializable()
   * @model
   * @generated
   */
  String getSerializable();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.VoDefinition#getSerializable <em>Serializable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Serializable</em>' attribute.
   * @see #getSerializable()
   * @generated
   */
  void setSerializable(String value);

  /**
   * Returns the value of the '<em><b>Lombok Annotation</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.LombokAnnotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lombok Annotation</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_LombokAnnotation()
   * @model containment="true"
   * @generated
   */
  EList<LombokAnnotation> getLombokAnnotation();

  /**
   * Returns the value of the '<em><b>Exclusions</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.Exclusions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusions</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_Exclusions()
   * @model containment="true"
   * @generated
   */
  EList<Exclusions> getExclusions();

  /**
   * Returns the value of the '<em><b>Exclude All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclude All</em>' attribute.
   * @see #setExcludeAll(String)
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_ExcludeAll()
   * @model
   * @generated
   */
  String getExcludeAll();

  /**
   * Sets the value of the '{@link com.yunzhi.genoMate.VoDefinition#getExcludeAll <em>Exclude All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclude All</em>' attribute.
   * @see #getExcludeAll()
   * @generated
   */
  void setExcludeAll(String value);

  /**
   * Returns the value of the '<em><b>Jacksons</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.VoJackson}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jacksons</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_Jacksons()
   * @model containment="true"
   * @generated
   */
  EList<VoJackson> getJacksons();

  /**
   * Returns the value of the '<em><b>Add Field</b></em>' containment reference list.
   * The list contents are of type {@link com.yunzhi.genoMate.VoAddField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Field</em>' containment reference list.
   * @see com.yunzhi.genoMate.GenoMatePackage#getVoDefinition_AddField()
   * @model containment="true"
   * @generated
   */
  EList<VoAddField> getAddField();

} // VoDefinition
