/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate.impl;

import com.yunzhi.genoMate.BeanValidationAnnotation;
import com.yunzhi.genoMate.DtoAddField;
import com.yunzhi.genoMate.GenoMatePackage;
import com.yunzhi.genoMate.PropertyDeclaration;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dto Add Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.impl.DtoAddFieldImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.impl.DtoAddFieldImpl#getAnnotationList <em>Annotation List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DtoAddFieldImpl extends MinimalEObjectImpl.Container implements DtoAddField
{
  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected PropertyDeclaration properties;

  /**
   * The cached value of the '{@link #getAnnotationList() <em>Annotation List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotationList()
   * @generated
   * @ordered
   */
  protected EList<BeanValidationAnnotation> annotationList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DtoAddFieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GenoMatePackage.Literals.DTO_ADD_FIELD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PropertyDeclaration getProperties()
  {
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProperties(PropertyDeclaration newProperties, NotificationChain msgs)
  {
    PropertyDeclaration oldProperties = properties;
    properties = newProperties;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GenoMatePackage.DTO_ADD_FIELD__PROPERTIES, oldProperties, newProperties);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProperties(PropertyDeclaration newProperties)
  {
    if (newProperties != properties)
    {
      NotificationChain msgs = null;
      if (properties != null)
        msgs = ((InternalEObject)properties).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GenoMatePackage.DTO_ADD_FIELD__PROPERTIES, null, msgs);
      if (newProperties != null)
        msgs = ((InternalEObject)newProperties).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GenoMatePackage.DTO_ADD_FIELD__PROPERTIES, null, msgs);
      msgs = basicSetProperties(newProperties, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenoMatePackage.DTO_ADD_FIELD__PROPERTIES, newProperties, newProperties));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BeanValidationAnnotation> getAnnotationList()
  {
    if (annotationList == null)
    {
      annotationList = new EObjectContainmentEList<BeanValidationAnnotation>(BeanValidationAnnotation.class, this, GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST);
    }
    return annotationList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GenoMatePackage.DTO_ADD_FIELD__PROPERTIES:
        return basicSetProperties(null, msgs);
      case GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST:
        return ((InternalEList<?>)getAnnotationList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GenoMatePackage.DTO_ADD_FIELD__PROPERTIES:
        return getProperties();
      case GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST:
        return getAnnotationList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GenoMatePackage.DTO_ADD_FIELD__PROPERTIES:
        setProperties((PropertyDeclaration)newValue);
        return;
      case GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST:
        getAnnotationList().clear();
        getAnnotationList().addAll((Collection<? extends BeanValidationAnnotation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GenoMatePackage.DTO_ADD_FIELD__PROPERTIES:
        setProperties((PropertyDeclaration)null);
        return;
      case GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST:
        getAnnotationList().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GenoMatePackage.DTO_ADD_FIELD__PROPERTIES:
        return properties != null;
      case GenoMatePackage.DTO_ADD_FIELD__ANNOTATION_LIST:
        return annotationList != null && !annotationList.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DtoAddFieldImpl
