/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate.impl;

import com.yunzhi.genoMate.AndTypeCondition;
import com.yunzhi.genoMate.AnnotationParameters;
import com.yunzhi.genoMate.ArrayType;
import com.yunzhi.genoMate.BeanValidationAnnotation;
import com.yunzhi.genoMate.BeanValidationType;
import com.yunzhi.genoMate.BuiltInType;
import com.yunzhi.genoMate.DTOToModelMapping;
import com.yunzhi.genoMate.DtoAddField;
import com.yunzhi.genoMate.DtoDefinition;
import com.yunzhi.genoMate.DtoRule;
import com.yunzhi.genoMate.DtoValidation;
import com.yunzhi.genoMate.Exclusions;
import com.yunzhi.genoMate.Field;
import com.yunzhi.genoMate.FieldAnnotation;
import com.yunzhi.genoMate.FieldValidationBlock;
import com.yunzhi.genoMate.GenerateSection;
import com.yunzhi.genoMate.GenerationRule;
import com.yunzhi.genoMate.GenericDataType;
import com.yunzhi.genoMate.GenoMate;
import com.yunzhi.genoMate.GenoMateFactory;
import com.yunzhi.genoMate.GenoMatePackage;
import com.yunzhi.genoMate.GlobalAction;
import com.yunzhi.genoMate.GlobalConfig;
import com.yunzhi.genoMate.JacksonAnnotation;
import com.yunzhi.genoMate.JacksonType;
import com.yunzhi.genoMate.LocalAction;
import com.yunzhi.genoMate.LocalLoopAction;
import com.yunzhi.genoMate.LombokAnnotation;
import com.yunzhi.genoMate.LombokType;
import com.yunzhi.genoMate.Mapping;
import com.yunzhi.genoMate.MappingRule;
import com.yunzhi.genoMate.Model;
import com.yunzhi.genoMate.ModelToVOMapping;
import com.yunzhi.genoMate.MybatisPlusFieldAnnotation;
import com.yunzhi.genoMate.MybatisPlusFieldType;
import com.yunzhi.genoMate.MybatisPlusModelAnnotation;
import com.yunzhi.genoMate.MybatisPlusModelType;
import com.yunzhi.genoMate.NormalType;
import com.yunzhi.genoMate.OrTypeCondition;
import com.yunzhi.genoMate.Parameter;
import com.yunzhi.genoMate.PoAddField;
import com.yunzhi.genoMate.PoRule;
import com.yunzhi.genoMate.PropertyDeclaration;
import com.yunzhi.genoMate.SimpleType;
import com.yunzhi.genoMate.SingleAction;
import com.yunzhi.genoMate.Type;
import com.yunzhi.genoMate.TypeCondition;
import com.yunzhi.genoMate.TypeEqualityCondition;
import com.yunzhi.genoMate.VariableDeclaration;
import com.yunzhi.genoMate.VoAddField;
import com.yunzhi.genoMate.VoDefinition;
import com.yunzhi.genoMate.VoJackson;
import com.yunzhi.genoMate.VoRule;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GenoMatePackageImpl extends EPackageImpl implements GenoMatePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass genoMateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass globalConfigEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lombokAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mybatisPlusModelAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mybatisPlusFieldAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass beanValidationAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jacksonAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass annotationParametersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generateSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generationRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass poRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass voRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass voDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fieldAnnotationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fieldValidationBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass localLoopActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass globalActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass localActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeConditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass orTypeConditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass andTypeConditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeEqualityConditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass poAddFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoAddFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass voAddFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exclusionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoValidationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass voJacksonEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass propertyDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelToVOMappingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoToModelMappingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass normalTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass genericDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arrayTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum beanValidationTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum mybatisPlusModelTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum mybatisPlusFieldTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jacksonTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum lombokTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum builtInTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.yunzhi.genoMate.GenoMatePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private GenoMatePackageImpl()
  {
    super(eNS_URI, GenoMateFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link GenoMatePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static GenoMatePackage init()
  {
    if (isInited) return (GenoMatePackage)EPackage.Registry.INSTANCE.getEPackage(GenoMatePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredGenoMatePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    GenoMatePackageImpl theGenoMatePackage = registeredGenoMatePackage instanceof GenoMatePackageImpl ? (GenoMatePackageImpl)registeredGenoMatePackage : new GenoMatePackageImpl();

    isInited = true;

    // Create package meta-data objects
    theGenoMatePackage.createPackageContents();

    // Initialize created meta-data
    theGenoMatePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theGenoMatePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(GenoMatePackage.eNS_URI, theGenoMatePackage);
    return theGenoMatePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenoMate()
  {
    return genoMateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenoMate_GlobalConfig()
  {
    return (EReference)genoMateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenoMate_Model()
  {
    return (EReference)genoMateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenoMate_GenerateSection()
  {
    return (EReference)genoMateEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenoMate_Mappings()
  {
    return (EReference)genoMateEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGlobalConfig()
  {
    return globalConfigEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalConfig_Package()
  {
    return (EAttribute)globalConfigEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGlobalConfig_VarDefaultAnnotations()
  {
    return (EReference)globalConfigEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Name()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Fields()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getField()
  {
    return fieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getField_Type()
  {
    return (EReference)fieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getField_Name()
  {
    return (EAttribute)fieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLombokAnnotation()
  {
    return lombokAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLombokAnnotation_Name()
  {
    return (EAttribute)lombokAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLombokAnnotation_Parameters()
  {
    return (EReference)lombokAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMybatisPlusModelAnnotation()
  {
    return mybatisPlusModelAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMybatisPlusModelAnnotation_Name()
  {
    return (EAttribute)mybatisPlusModelAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMybatisPlusModelAnnotation_Parameters()
  {
    return (EReference)mybatisPlusModelAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMybatisPlusFieldAnnotation()
  {
    return mybatisPlusFieldAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMybatisPlusFieldAnnotation_Name()
  {
    return (EAttribute)mybatisPlusFieldAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMybatisPlusFieldAnnotation_Parameters()
  {
    return (EReference)mybatisPlusFieldAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBeanValidationAnnotation()
  {
    return beanValidationAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBeanValidationAnnotation_Name()
  {
    return (EAttribute)beanValidationAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBeanValidationAnnotation_Parameters()
  {
    return (EReference)beanValidationAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJacksonAnnotation()
  {
    return jacksonAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJacksonAnnotation_Name()
  {
    return (EAttribute)jacksonAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJacksonAnnotation_Parameters()
  {
    return (EReference)jacksonAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAnnotationParameters()
  {
    return annotationParametersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAnnotationParameters_Annparameters()
  {
    return (EReference)annotationParametersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAnnotationParameters_Parameters()
  {
    return (EReference)annotationParametersEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParameter()
  {
    return parameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getParameter_Key()
  {
    return (EAttribute)parameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getParameter_Value()
  {
    return (EAttribute)parameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenerateSection()
  {
    return generateSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerateSection_Rules()
  {
    return (EReference)generateSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenerationRule()
  {
    return generationRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationRule_Model()
  {
    return (EReference)generationRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPoRule()
  {
    return poRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPoRule_Serializable()
  {
    return (EAttribute)poRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoRule_LombokAnnotation()
  {
    return (EReference)poRuleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoRule_MybatisPlusModelAnnotation()
  {
    return (EReference)poRuleEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoRule_FieldAnns()
  {
    return (EReference)poRuleEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoRule_AddField()
  {
    return (EReference)poRuleEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDtoRule()
  {
    return dtoRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoRule_Dtos()
  {
    return (EReference)dtoRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVoRule()
  {
    return voRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoRule_Vos()
  {
    return (EReference)voRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDtoDefinition()
  {
    return dtoDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDtoDefinition_Name()
  {
    return (EAttribute)dtoDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDtoDefinition_Serializable()
  {
    return (EAttribute)dtoDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoDefinition_LombokAnnotation()
  {
    return (EReference)dtoDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoDefinition_Exclusions()
  {
    return (EReference)dtoDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDtoDefinition_ExcludeAll()
  {
    return (EAttribute)dtoDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoDefinition_FieldAnnotationsBlock()
  {
    return (EReference)dtoDefinitionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoDefinition_AddField()
  {
    return (EReference)dtoDefinitionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVoDefinition()
  {
    return voDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVoDefinition_Name()
  {
    return (EAttribute)voDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVoDefinition_Serializable()
  {
    return (EAttribute)voDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoDefinition_LombokAnnotation()
  {
    return (EReference)voDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoDefinition_Exclusions()
  {
    return (EReference)voDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVoDefinition_ExcludeAll()
  {
    return (EAttribute)voDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoDefinition_Jacksons()
  {
    return (EReference)voDefinitionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoDefinition_AddField()
  {
    return (EReference)voDefinitionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFieldAnnotation()
  {
    return fieldAnnotationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFieldAnnotation_Field()
  {
    return (EReference)fieldAnnotationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFieldAnnotation_AnnList()
  {
    return (EReference)fieldAnnotationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFieldValidationBlock()
  {
    return fieldValidationBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFieldValidationBlock_ActionGlobal()
  {
    return (EReference)fieldValidationBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFieldValidationBlock_ActionLocal()
  {
    return (EReference)fieldValidationBlockEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFieldValidationBlock_ActionSingle()
  {
    return (EReference)fieldValidationBlockEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSingleAction()
  {
    return singleActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSingleAction_Validations()
  {
    return (EReference)singleActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLocalLoopAction()
  {
    return localLoopActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocalLoopAction_VarDeclarations()
  {
    return (EReference)localLoopActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocalLoopAction_Actions()
  {
    return (EReference)localLoopActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGlobalAction()
  {
    return globalActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGlobalAction_Variable()
  {
    return (EReference)globalActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLocalAction()
  {
    return localActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocalAction_Condition()
  {
    return (EReference)localActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocalAction_Variable()
  {
    return (EReference)localActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypeCondition()
  {
    return typeConditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOrTypeCondition()
  {
    return orTypeConditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOrTypeCondition_Left()
  {
    return (EReference)orTypeConditionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOrTypeCondition_Right()
  {
    return (EReference)orTypeConditionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAndTypeCondition()
  {
    return andTypeConditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAndTypeCondition_Left()
  {
    return (EReference)andTypeConditionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAndTypeCondition_Right()
  {
    return (EReference)andTypeConditionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypeEqualityCondition()
  {
    return typeEqualityConditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypeEqualityCondition_IsEqual()
  {
    return (EAttribute)typeEqualityConditionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypeEqualityCondition_IsNotEqual()
  {
    return (EAttribute)typeEqualityConditionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTypeEqualityCondition_Type()
  {
    return (EReference)typeEqualityConditionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariableDeclaration()
  {
    return variableDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariableDeclaration_Name()
  {
    return (EAttribute)variableDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariableDeclaration_Annotation()
  {
    return (EReference)variableDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPoAddField()
  {
    return poAddFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoAddField_Properties()
  {
    return (EReference)poAddFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPoAddField_AnnotationList()
  {
    return (EReference)poAddFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDtoAddField()
  {
    return dtoAddFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoAddField_Properties()
  {
    return (EReference)dtoAddFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoAddField_AnnotationList()
  {
    return (EReference)dtoAddFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVoAddField()
  {
    return voAddFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoAddField_Properties()
  {
    return (EReference)voAddFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoAddField_AnnotationList()
  {
    return (EReference)voAddFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExclusions()
  {
    return exclusionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExclusions_Field()
  {
    return (EReference)exclusionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDtoValidation()
  {
    return dtoValidationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoValidation_Field()
  {
    return (EReference)dtoValidationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDtoValidation_AnnList()
  {
    return (EReference)dtoValidationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVoJackson()
  {
    return voJacksonEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoJackson_Field()
  {
    return (EReference)voJacksonEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVoJackson_AnnList()
  {
    return (EReference)voJacksonEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPropertyDeclaration()
  {
    return propertyDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDeclaration_Static()
  {
    return (EAttribute)propertyDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDeclaration_Final()
  {
    return (EAttribute)propertyDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPropertyDeclaration_Type()
  {
    return (EReference)propertyDeclarationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDeclaration_Name()
  {
    return (EAttribute)propertyDeclarationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDeclaration_DefaultClause()
  {
    return (EAttribute)propertyDeclarationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMapping()
  {
    return mappingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMapping_Rules()
  {
    return (EReference)mappingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelToVOMapping()
  {
    return modelToVOMappingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelToVOMapping_Source()
  {
    return (EReference)modelToVOMappingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelToVOMapping_Target()
  {
    return (EReference)modelToVOMappingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDTOToModelMapping()
  {
    return dtoToModelMappingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDTOToModelMapping_Source()
  {
    return (EReference)dtoToModelMappingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDTOToModelMapping_Target()
  {
    return (EReference)dtoToModelMappingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMappingRule()
  {
    return mappingRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMappingRule_TargetField()
  {
    return (EReference)mappingRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMappingRule_SourceField()
  {
    return (EReference)mappingRuleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMappingRule_Default()
  {
    return (EAttribute)mappingRuleEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getType()
  {
    return typeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSimpleType()
  {
    return simpleTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSimpleType_BuiltInType()
  {
    return (EAttribute)simpleTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNormalType()
  {
    return normalTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNormalType_CustomType()
  {
    return (EAttribute)normalTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenericDataType()
  {
    return genericDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenericDataType_ContainerTypeName()
  {
    return (EAttribute)genericDataTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenericDataType_ContainedTypeName()
  {
    return (EReference)genericDataTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArrayType()
  {
    return arrayTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArrayType_ElementType()
  {
    return (EReference)arrayTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getBeanValidationType()
  {
    return beanValidationTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getMybatisPlusModelType()
  {
    return mybatisPlusModelTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getMybatisPlusFieldType()
  {
    return mybatisPlusFieldTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getJacksonType()
  {
    return jacksonTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getLombokType()
  {
    return lombokTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getBuiltInType()
  {
    return builtInTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GenoMateFactory getGenoMateFactory()
  {
    return (GenoMateFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    genoMateEClass = createEClass(GENO_MATE);
    createEReference(genoMateEClass, GENO_MATE__GLOBAL_CONFIG);
    createEReference(genoMateEClass, GENO_MATE__MODEL);
    createEReference(genoMateEClass, GENO_MATE__GENERATE_SECTION);
    createEReference(genoMateEClass, GENO_MATE__MAPPINGS);

    globalConfigEClass = createEClass(GLOBAL_CONFIG);
    createEAttribute(globalConfigEClass, GLOBAL_CONFIG__PACKAGE);
    createEReference(globalConfigEClass, GLOBAL_CONFIG__VAR_DEFAULT_ANNOTATIONS);

    modelEClass = createEClass(MODEL);
    createEAttribute(modelEClass, MODEL__NAME);
    createEReference(modelEClass, MODEL__FIELDS);

    fieldEClass = createEClass(FIELD);
    createEReference(fieldEClass, FIELD__TYPE);
    createEAttribute(fieldEClass, FIELD__NAME);

    lombokAnnotationEClass = createEClass(LOMBOK_ANNOTATION);
    createEAttribute(lombokAnnotationEClass, LOMBOK_ANNOTATION__NAME);
    createEReference(lombokAnnotationEClass, LOMBOK_ANNOTATION__PARAMETERS);

    mybatisPlusModelAnnotationEClass = createEClass(MYBATIS_PLUS_MODEL_ANNOTATION);
    createEAttribute(mybatisPlusModelAnnotationEClass, MYBATIS_PLUS_MODEL_ANNOTATION__NAME);
    createEReference(mybatisPlusModelAnnotationEClass, MYBATIS_PLUS_MODEL_ANNOTATION__PARAMETERS);

    mybatisPlusFieldAnnotationEClass = createEClass(MYBATIS_PLUS_FIELD_ANNOTATION);
    createEAttribute(mybatisPlusFieldAnnotationEClass, MYBATIS_PLUS_FIELD_ANNOTATION__NAME);
    createEReference(mybatisPlusFieldAnnotationEClass, MYBATIS_PLUS_FIELD_ANNOTATION__PARAMETERS);

    beanValidationAnnotationEClass = createEClass(BEAN_VALIDATION_ANNOTATION);
    createEAttribute(beanValidationAnnotationEClass, BEAN_VALIDATION_ANNOTATION__NAME);
    createEReference(beanValidationAnnotationEClass, BEAN_VALIDATION_ANNOTATION__PARAMETERS);

    jacksonAnnotationEClass = createEClass(JACKSON_ANNOTATION);
    createEAttribute(jacksonAnnotationEClass, JACKSON_ANNOTATION__NAME);
    createEReference(jacksonAnnotationEClass, JACKSON_ANNOTATION__PARAMETERS);

    annotationParametersEClass = createEClass(ANNOTATION_PARAMETERS);
    createEReference(annotationParametersEClass, ANNOTATION_PARAMETERS__ANNPARAMETERS);
    createEReference(annotationParametersEClass, ANNOTATION_PARAMETERS__PARAMETERS);

    parameterEClass = createEClass(PARAMETER);
    createEAttribute(parameterEClass, PARAMETER__KEY);
    createEAttribute(parameterEClass, PARAMETER__VALUE);

    generateSectionEClass = createEClass(GENERATE_SECTION);
    createEReference(generateSectionEClass, GENERATE_SECTION__RULES);

    generationRuleEClass = createEClass(GENERATION_RULE);
    createEReference(generationRuleEClass, GENERATION_RULE__MODEL);

    poRuleEClass = createEClass(PO_RULE);
    createEAttribute(poRuleEClass, PO_RULE__SERIALIZABLE);
    createEReference(poRuleEClass, PO_RULE__LOMBOK_ANNOTATION);
    createEReference(poRuleEClass, PO_RULE__MYBATIS_PLUS_MODEL_ANNOTATION);
    createEReference(poRuleEClass, PO_RULE__FIELD_ANNS);
    createEReference(poRuleEClass, PO_RULE__ADD_FIELD);

    dtoRuleEClass = createEClass(DTO_RULE);
    createEReference(dtoRuleEClass, DTO_RULE__DTOS);

    voRuleEClass = createEClass(VO_RULE);
    createEReference(voRuleEClass, VO_RULE__VOS);

    dtoDefinitionEClass = createEClass(DTO_DEFINITION);
    createEAttribute(dtoDefinitionEClass, DTO_DEFINITION__NAME);
    createEAttribute(dtoDefinitionEClass, DTO_DEFINITION__SERIALIZABLE);
    createEReference(dtoDefinitionEClass, DTO_DEFINITION__LOMBOK_ANNOTATION);
    createEReference(dtoDefinitionEClass, DTO_DEFINITION__EXCLUSIONS);
    createEAttribute(dtoDefinitionEClass, DTO_DEFINITION__EXCLUDE_ALL);
    createEReference(dtoDefinitionEClass, DTO_DEFINITION__FIELD_ANNOTATIONS_BLOCK);
    createEReference(dtoDefinitionEClass, DTO_DEFINITION__ADD_FIELD);

    voDefinitionEClass = createEClass(VO_DEFINITION);
    createEAttribute(voDefinitionEClass, VO_DEFINITION__NAME);
    createEAttribute(voDefinitionEClass, VO_DEFINITION__SERIALIZABLE);
    createEReference(voDefinitionEClass, VO_DEFINITION__LOMBOK_ANNOTATION);
    createEReference(voDefinitionEClass, VO_DEFINITION__EXCLUSIONS);
    createEAttribute(voDefinitionEClass, VO_DEFINITION__EXCLUDE_ALL);
    createEReference(voDefinitionEClass, VO_DEFINITION__JACKSONS);
    createEReference(voDefinitionEClass, VO_DEFINITION__ADD_FIELD);

    fieldAnnotationEClass = createEClass(FIELD_ANNOTATION);
    createEReference(fieldAnnotationEClass, FIELD_ANNOTATION__FIELD);
    createEReference(fieldAnnotationEClass, FIELD_ANNOTATION__ANN_LIST);

    fieldValidationBlockEClass = createEClass(FIELD_VALIDATION_BLOCK);
    createEReference(fieldValidationBlockEClass, FIELD_VALIDATION_BLOCK__ACTION_GLOBAL);
    createEReference(fieldValidationBlockEClass, FIELD_VALIDATION_BLOCK__ACTION_LOCAL);
    createEReference(fieldValidationBlockEClass, FIELD_VALIDATION_BLOCK__ACTION_SINGLE);

    singleActionEClass = createEClass(SINGLE_ACTION);
    createEReference(singleActionEClass, SINGLE_ACTION__VALIDATIONS);

    localLoopActionEClass = createEClass(LOCAL_LOOP_ACTION);
    createEReference(localLoopActionEClass, LOCAL_LOOP_ACTION__VAR_DECLARATIONS);
    createEReference(localLoopActionEClass, LOCAL_LOOP_ACTION__ACTIONS);

    globalActionEClass = createEClass(GLOBAL_ACTION);
    createEReference(globalActionEClass, GLOBAL_ACTION__VARIABLE);

    localActionEClass = createEClass(LOCAL_ACTION);
    createEReference(localActionEClass, LOCAL_ACTION__CONDITION);
    createEReference(localActionEClass, LOCAL_ACTION__VARIABLE);

    typeConditionEClass = createEClass(TYPE_CONDITION);

    orTypeConditionEClass = createEClass(OR_TYPE_CONDITION);
    createEReference(orTypeConditionEClass, OR_TYPE_CONDITION__LEFT);
    createEReference(orTypeConditionEClass, OR_TYPE_CONDITION__RIGHT);

    andTypeConditionEClass = createEClass(AND_TYPE_CONDITION);
    createEReference(andTypeConditionEClass, AND_TYPE_CONDITION__LEFT);
    createEReference(andTypeConditionEClass, AND_TYPE_CONDITION__RIGHT);

    typeEqualityConditionEClass = createEClass(TYPE_EQUALITY_CONDITION);
    createEAttribute(typeEqualityConditionEClass, TYPE_EQUALITY_CONDITION__IS_EQUAL);
    createEAttribute(typeEqualityConditionEClass, TYPE_EQUALITY_CONDITION__IS_NOT_EQUAL);
    createEReference(typeEqualityConditionEClass, TYPE_EQUALITY_CONDITION__TYPE);

    variableDeclarationEClass = createEClass(VARIABLE_DECLARATION);
    createEAttribute(variableDeclarationEClass, VARIABLE_DECLARATION__NAME);
    createEReference(variableDeclarationEClass, VARIABLE_DECLARATION__ANNOTATION);

    poAddFieldEClass = createEClass(PO_ADD_FIELD);
    createEReference(poAddFieldEClass, PO_ADD_FIELD__PROPERTIES);
    createEReference(poAddFieldEClass, PO_ADD_FIELD__ANNOTATION_LIST);

    dtoAddFieldEClass = createEClass(DTO_ADD_FIELD);
    createEReference(dtoAddFieldEClass, DTO_ADD_FIELD__PROPERTIES);
    createEReference(dtoAddFieldEClass, DTO_ADD_FIELD__ANNOTATION_LIST);

    voAddFieldEClass = createEClass(VO_ADD_FIELD);
    createEReference(voAddFieldEClass, VO_ADD_FIELD__PROPERTIES);
    createEReference(voAddFieldEClass, VO_ADD_FIELD__ANNOTATION_LIST);

    exclusionsEClass = createEClass(EXCLUSIONS);
    createEReference(exclusionsEClass, EXCLUSIONS__FIELD);

    dtoValidationEClass = createEClass(DTO_VALIDATION);
    createEReference(dtoValidationEClass, DTO_VALIDATION__FIELD);
    createEReference(dtoValidationEClass, DTO_VALIDATION__ANN_LIST);

    voJacksonEClass = createEClass(VO_JACKSON);
    createEReference(voJacksonEClass, VO_JACKSON__FIELD);
    createEReference(voJacksonEClass, VO_JACKSON__ANN_LIST);

    propertyDeclarationEClass = createEClass(PROPERTY_DECLARATION);
    createEAttribute(propertyDeclarationEClass, PROPERTY_DECLARATION__STATIC);
    createEAttribute(propertyDeclarationEClass, PROPERTY_DECLARATION__FINAL);
    createEReference(propertyDeclarationEClass, PROPERTY_DECLARATION__TYPE);
    createEAttribute(propertyDeclarationEClass, PROPERTY_DECLARATION__NAME);
    createEAttribute(propertyDeclarationEClass, PROPERTY_DECLARATION__DEFAULT_CLAUSE);

    mappingEClass = createEClass(MAPPING);
    createEReference(mappingEClass, MAPPING__RULES);

    modelToVOMappingEClass = createEClass(MODEL_TO_VO_MAPPING);
    createEReference(modelToVOMappingEClass, MODEL_TO_VO_MAPPING__SOURCE);
    createEReference(modelToVOMappingEClass, MODEL_TO_VO_MAPPING__TARGET);

    dtoToModelMappingEClass = createEClass(DTO_TO_MODEL_MAPPING);
    createEReference(dtoToModelMappingEClass, DTO_TO_MODEL_MAPPING__SOURCE);
    createEReference(dtoToModelMappingEClass, DTO_TO_MODEL_MAPPING__TARGET);

    mappingRuleEClass = createEClass(MAPPING_RULE);
    createEReference(mappingRuleEClass, MAPPING_RULE__TARGET_FIELD);
    createEReference(mappingRuleEClass, MAPPING_RULE__SOURCE_FIELD);
    createEAttribute(mappingRuleEClass, MAPPING_RULE__DEFAULT);

    typeEClass = createEClass(TYPE);

    simpleTypeEClass = createEClass(SIMPLE_TYPE);
    createEAttribute(simpleTypeEClass, SIMPLE_TYPE__BUILT_IN_TYPE);

    normalTypeEClass = createEClass(NORMAL_TYPE);
    createEAttribute(normalTypeEClass, NORMAL_TYPE__CUSTOM_TYPE);

    genericDataTypeEClass = createEClass(GENERIC_DATA_TYPE);
    createEAttribute(genericDataTypeEClass, GENERIC_DATA_TYPE__CONTAINER_TYPE_NAME);
    createEReference(genericDataTypeEClass, GENERIC_DATA_TYPE__CONTAINED_TYPE_NAME);

    arrayTypeEClass = createEClass(ARRAY_TYPE);
    createEReference(arrayTypeEClass, ARRAY_TYPE__ELEMENT_TYPE);

    // Create enums
    beanValidationTypeEEnum = createEEnum(BEAN_VALIDATION_TYPE);
    mybatisPlusModelTypeEEnum = createEEnum(MYBATIS_PLUS_MODEL_TYPE);
    mybatisPlusFieldTypeEEnum = createEEnum(MYBATIS_PLUS_FIELD_TYPE);
    jacksonTypeEEnum = createEEnum(JACKSON_TYPE);
    lombokTypeEEnum = createEEnum(LOMBOK_TYPE);
    builtInTypeEEnum = createEEnum(BUILT_IN_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    poRuleEClass.getESuperTypes().add(this.getGenerationRule());
    dtoRuleEClass.getESuperTypes().add(this.getGenerationRule());
    voRuleEClass.getESuperTypes().add(this.getGenerationRule());
    orTypeConditionEClass.getESuperTypes().add(this.getTypeCondition());
    modelToVOMappingEClass.getESuperTypes().add(this.getMapping());
    dtoToModelMappingEClass.getESuperTypes().add(this.getMapping());
    simpleTypeEClass.getESuperTypes().add(this.getType());
    normalTypeEClass.getESuperTypes().add(this.getType());
    genericDataTypeEClass.getESuperTypes().add(this.getType());
    arrayTypeEClass.getESuperTypes().add(this.getType());

    // Initialize classes and features; add operations and parameters
    initEClass(genoMateEClass, GenoMate.class, "GenoMate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGenoMate_GlobalConfig(), this.getGlobalConfig(), null, "globalConfig", null, 0, 1, GenoMate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenoMate_Model(), this.getModel(), null, "model", null, 0, 1, GenoMate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenoMate_GenerateSection(), this.getGenerateSection(), null, "generateSection", null, 0, 1, GenoMate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenoMate_Mappings(), this.getMapping(), null, "mappings", null, 0, -1, GenoMate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(globalConfigEClass, GlobalConfig.class, "GlobalConfig", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlobalConfig_Package(), ecorePackage.getEString(), "package", null, 0, 1, GlobalConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGlobalConfig_VarDefaultAnnotations(), this.getVariableDeclaration(), null, "varDefaultAnnotations", null, 0, -1, GlobalConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModel_Name(), ecorePackage.getEString(), "name", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Fields(), this.getField(), null, "fields", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fieldEClass, Field.class, "Field", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getField_Type(), this.getType(), null, "type", null, 0, 1, Field.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getField_Name(), ecorePackage.getEString(), "name", null, 0, 1, Field.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lombokAnnotationEClass, LombokAnnotation.class, "LombokAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLombokAnnotation_Name(), this.getLombokType(), "name", null, 0, 1, LombokAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLombokAnnotation_Parameters(), this.getAnnotationParameters(), null, "parameters", null, 0, 1, LombokAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mybatisPlusModelAnnotationEClass, MybatisPlusModelAnnotation.class, "MybatisPlusModelAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMybatisPlusModelAnnotation_Name(), this.getMybatisPlusModelType(), "name", null, 0, 1, MybatisPlusModelAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMybatisPlusModelAnnotation_Parameters(), this.getAnnotationParameters(), null, "parameters", null, 0, 1, MybatisPlusModelAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mybatisPlusFieldAnnotationEClass, MybatisPlusFieldAnnotation.class, "MybatisPlusFieldAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMybatisPlusFieldAnnotation_Name(), this.getMybatisPlusFieldType(), "name", null, 0, 1, MybatisPlusFieldAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMybatisPlusFieldAnnotation_Parameters(), this.getAnnotationParameters(), null, "parameters", null, 0, 1, MybatisPlusFieldAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(beanValidationAnnotationEClass, BeanValidationAnnotation.class, "BeanValidationAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBeanValidationAnnotation_Name(), this.getBeanValidationType(), "name", null, 0, 1, BeanValidationAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBeanValidationAnnotation_Parameters(), this.getAnnotationParameters(), null, "parameters", null, 0, 1, BeanValidationAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jacksonAnnotationEClass, JacksonAnnotation.class, "JacksonAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJacksonAnnotation_Name(), this.getJacksonType(), "name", null, 0, 1, JacksonAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJacksonAnnotation_Parameters(), this.getAnnotationParameters(), null, "parameters", null, 0, 1, JacksonAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(annotationParametersEClass, AnnotationParameters.class, "AnnotationParameters", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAnnotationParameters_Annparameters(), this.getParameter(), null, "annparameters", null, 0, -1, AnnotationParameters.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnnotationParameters_Parameters(), this.getParameter(), null, "parameters", null, 0, -1, AnnotationParameters.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parameterEClass, Parameter.class, "Parameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getParameter_Key(), ecorePackage.getEString(), "key", null, 0, 1, Parameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getParameter_Value(), ecorePackage.getEString(), "value", null, 0, 1, Parameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(generateSectionEClass, GenerateSection.class, "GenerateSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGenerateSection_Rules(), this.getGenerationRule(), null, "rules", null, 0, -1, GenerateSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(generationRuleEClass, GenerationRule.class, "GenerationRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGenerationRule_Model(), this.getModel(), null, "model", null, 0, 1, GenerationRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(poRuleEClass, PoRule.class, "PoRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPoRule_Serializable(), ecorePackage.getEString(), "serializable", null, 0, 1, PoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPoRule_LombokAnnotation(), this.getLombokAnnotation(), null, "lombokAnnotation", null, 0, -1, PoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPoRule_MybatisPlusModelAnnotation(), this.getMybatisPlusModelAnnotation(), null, "mybatisPlusModelAnnotation", null, 0, -1, PoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPoRule_FieldAnns(), this.getFieldAnnotation(), null, "fieldAnns", null, 0, -1, PoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPoRule_AddField(), this.getPoAddField(), null, "addField", null, 0, -1, PoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoRuleEClass, DtoRule.class, "DtoRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtoRule_Dtos(), this.getDtoDefinition(), null, "dtos", null, 0, -1, DtoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(voRuleEClass, VoRule.class, "VoRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVoRule_Vos(), this.getVoDefinition(), null, "vos", null, 0, -1, VoRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoDefinitionEClass, DtoDefinition.class, "DtoDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtoDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtoDefinition_Serializable(), ecorePackage.getEString(), "serializable", null, 0, 1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoDefinition_LombokAnnotation(), this.getLombokAnnotation(), null, "lombokAnnotation", null, 0, -1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoDefinition_Exclusions(), this.getExclusions(), null, "exclusions", null, 0, -1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtoDefinition_ExcludeAll(), ecorePackage.getEString(), "excludeAll", null, 0, 1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoDefinition_FieldAnnotationsBlock(), this.getFieldValidationBlock(), null, "fieldAnnotationsBlock", null, 0, 1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoDefinition_AddField(), this.getDtoAddField(), null, "addField", null, 0, -1, DtoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(voDefinitionEClass, VoDefinition.class, "VoDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVoDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVoDefinition_Serializable(), ecorePackage.getEString(), "serializable", null, 0, 1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoDefinition_LombokAnnotation(), this.getLombokAnnotation(), null, "lombokAnnotation", null, 0, -1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoDefinition_Exclusions(), this.getExclusions(), null, "exclusions", null, 0, -1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVoDefinition_ExcludeAll(), ecorePackage.getEString(), "excludeAll", null, 0, 1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoDefinition_Jacksons(), this.getVoJackson(), null, "jacksons", null, 0, -1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoDefinition_AddField(), this.getVoAddField(), null, "addField", null, 0, -1, VoDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fieldAnnotationEClass, FieldAnnotation.class, "FieldAnnotation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFieldAnnotation_Field(), this.getField(), null, "field", null, 0, 1, FieldAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFieldAnnotation_AnnList(), this.getMybatisPlusFieldAnnotation(), null, "annList", null, 0, -1, FieldAnnotation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fieldValidationBlockEClass, FieldValidationBlock.class, "FieldValidationBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFieldValidationBlock_ActionGlobal(), this.getGlobalAction(), null, "actionGlobal", null, 0, -1, FieldValidationBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFieldValidationBlock_ActionLocal(), this.getLocalLoopAction(), null, "actionLocal", null, 0, -1, FieldValidationBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFieldValidationBlock_ActionSingle(), this.getSingleAction(), null, "actionSingle", null, 0, 1, FieldValidationBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleActionEClass, SingleAction.class, "SingleAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSingleAction_Validations(), this.getDtoValidation(), null, "validations", null, 0, -1, SingleAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(localLoopActionEClass, LocalLoopAction.class, "LocalLoopAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLocalLoopAction_VarDeclarations(), this.getVariableDeclaration(), null, "varDeclarations", null, 0, -1, LocalLoopAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLocalLoopAction_Actions(), this.getLocalAction(), null, "actions", null, 0, -1, LocalLoopAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(globalActionEClass, GlobalAction.class, "GlobalAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGlobalAction_Variable(), this.getVariableDeclaration(), null, "variable", null, 0, 1, GlobalAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(localActionEClass, LocalAction.class, "LocalAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLocalAction_Condition(), this.getTypeCondition(), null, "condition", null, 0, 1, LocalAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLocalAction_Variable(), this.getVariableDeclaration(), null, "variable", null, 0, 1, LocalAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeConditionEClass, TypeCondition.class, "TypeCondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(orTypeConditionEClass, OrTypeCondition.class, "OrTypeCondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOrTypeCondition_Left(), this.getAndTypeCondition(), null, "left", null, 0, 1, OrTypeCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOrTypeCondition_Right(), this.getAndTypeCondition(), null, "right", null, 0, -1, OrTypeCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(andTypeConditionEClass, AndTypeCondition.class, "AndTypeCondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAndTypeCondition_Left(), this.getTypeEqualityCondition(), null, "left", null, 0, 1, AndTypeCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAndTypeCondition_Right(), this.getTypeEqualityCondition(), null, "right", null, 0, -1, AndTypeCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeEqualityConditionEClass, TypeEqualityCondition.class, "TypeEqualityCondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypeEqualityCondition_IsEqual(), ecorePackage.getEString(), "isEqual", null, 0, 1, TypeEqualityCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeEqualityCondition_IsNotEqual(), ecorePackage.getEString(), "isNotEqual", null, 0, 1, TypeEqualityCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTypeEqualityCondition_Type(), this.getType(), null, "type", null, 0, 1, TypeEqualityCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableDeclarationEClass, VariableDeclaration.class, "VariableDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVariableDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, VariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVariableDeclaration_Annotation(), this.getBeanValidationAnnotation(), null, "annotation", null, 0, 1, VariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(poAddFieldEClass, PoAddField.class, "PoAddField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPoAddField_Properties(), this.getPropertyDeclaration(), null, "properties", null, 0, 1, PoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPoAddField_AnnotationList(), this.getMybatisPlusFieldAnnotation(), null, "annotationList", null, 0, -1, PoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoAddFieldEClass, DtoAddField.class, "DtoAddField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtoAddField_Properties(), this.getPropertyDeclaration(), null, "properties", null, 0, 1, DtoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoAddField_AnnotationList(), this.getBeanValidationAnnotation(), null, "annotationList", null, 0, -1, DtoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(voAddFieldEClass, VoAddField.class, "VoAddField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVoAddField_Properties(), this.getPropertyDeclaration(), null, "properties", null, 0, 1, VoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoAddField_AnnotationList(), this.getJacksonAnnotation(), null, "annotationList", null, 0, -1, VoAddField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exclusionsEClass, Exclusions.class, "Exclusions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExclusions_Field(), this.getField(), null, "field", null, 0, 1, Exclusions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoValidationEClass, DtoValidation.class, "DtoValidation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtoValidation_Field(), this.getField(), null, "field", null, 0, 1, DtoValidation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtoValidation_AnnList(), this.getBeanValidationAnnotation(), null, "annList", null, 0, -1, DtoValidation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(voJacksonEClass, VoJackson.class, "VoJackson", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVoJackson_Field(), this.getField(), null, "field", null, 0, 1, VoJackson.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVoJackson_AnnList(), this.getJacksonAnnotation(), null, "annList", null, 0, -1, VoJackson.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(propertyDeclarationEClass, PropertyDeclaration.class, "PropertyDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPropertyDeclaration_Static(), ecorePackage.getEString(), "static", null, 0, 1, PropertyDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPropertyDeclaration_Final(), ecorePackage.getEString(), "final", null, 0, 1, PropertyDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPropertyDeclaration_Type(), this.getType(), null, "type", null, 0, 1, PropertyDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPropertyDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, PropertyDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPropertyDeclaration_DefaultClause(), ecorePackage.getEString(), "defaultClause", null, 0, 1, PropertyDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mappingEClass, Mapping.class, "Mapping", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMapping_Rules(), this.getMappingRule(), null, "rules", null, 0, -1, Mapping.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelToVOMappingEClass, ModelToVOMapping.class, "ModelToVOMapping", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelToVOMapping_Source(), this.getModel(), null, "source", null, 0, 1, ModelToVOMapping.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelToVOMapping_Target(), this.getVoDefinition(), null, "target", null, 0, 1, ModelToVOMapping.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoToModelMappingEClass, DTOToModelMapping.class, "DTOToModelMapping", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDTOToModelMapping_Source(), this.getDtoDefinition(), null, "source", null, 0, 1, DTOToModelMapping.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDTOToModelMapping_Target(), this.getModel(), null, "target", null, 0, 1, DTOToModelMapping.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mappingRuleEClass, MappingRule.class, "MappingRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMappingRule_TargetField(), this.getField(), null, "targetField", null, 0, 1, MappingRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMappingRule_SourceField(), this.getField(), null, "sourceField", null, 0, 1, MappingRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMappingRule_Default(), ecorePackage.getEString(), "default", null, 0, 1, MappingRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeEClass, Type.class, "Type", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(simpleTypeEClass, SimpleType.class, "SimpleType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimpleType_BuiltInType(), this.getBuiltInType(), "builtInType", null, 0, 1, SimpleType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(normalTypeEClass, NormalType.class, "NormalType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNormalType_CustomType(), ecorePackage.getEString(), "customType", null, 0, 1, NormalType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(genericDataTypeEClass, GenericDataType.class, "GenericDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGenericDataType_ContainerTypeName(), ecorePackage.getEString(), "containerTypeName", null, 0, 1, GenericDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenericDataType_ContainedTypeName(), this.getType(), null, "containedTypeName", null, 0, 1, GenericDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arrayTypeEClass, ArrayType.class, "ArrayType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArrayType_ElementType(), this.getType(), null, "elementType", null, 0, 1, ArrayType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(beanValidationTypeEEnum, BeanValidationType.class, "BeanValidationType");
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.ASSERT_FALSE);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.ASSERT_TRUE);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.DECIMAL_MAX);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.DECIMAL_MIN);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.DIGITS);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.EMAIL);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.FUTURE);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.FUTURE_OR_PRESENT);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.MAX);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.MIN);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NEGATIVE);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NEGATIVE_OR_ZERO);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NOT_BLANK);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NOT_EMPTY);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NOT_NULL);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.NULL);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.PAST);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.PAST_OR_PRESENT);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.PATTERN);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.POSITIVE);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.POSITIVE_OR_ZERO);
    addEEnumLiteral(beanValidationTypeEEnum, BeanValidationType.SIZE);

    initEEnum(mybatisPlusModelTypeEEnum, MybatisPlusModelType.class, "MybatisPlusModelType");
    addEEnumLiteral(mybatisPlusModelTypeEEnum, MybatisPlusModelType.KEY_SEQUENCE);
    addEEnumLiteral(mybatisPlusModelTypeEEnum, MybatisPlusModelType.TABLE_NAME);

    initEEnum(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.class, "MybatisPlusFieldType");
    addEEnumLiteral(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.ORDER_BY);
    addEEnumLiteral(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.TABLE_FIELD);
    addEEnumLiteral(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.TABLE_ID);
    addEEnumLiteral(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.TABLE_LOGIC);
    addEEnumLiteral(mybatisPlusFieldTypeEEnum, MybatisPlusFieldType.VERSION);

    initEEnum(jacksonTypeEEnum, JacksonType.class, "JacksonType");
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_ALIAS);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_ANY_GETTER);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_ANY_SETTER);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_AUTO_DETECT);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_DESERIALIZE);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_FORMAT);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_IGNORE);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_IGNORE_PROPERTIES);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_INCLUDE);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_ROOT_NAME);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_SERIALIZE);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_TYPE_INFO);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_UNWRAPPED);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_VALUE);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_VIEW);
    addEEnumLiteral(jacksonTypeEEnum, JacksonType.JSON_PROPERTY);

    initEEnum(lombokTypeEEnum, LombokType.class, "LombokType");
    addEEnumLiteral(lombokTypeEEnum, LombokType.ACCESSORS);
    addEEnumLiteral(lombokTypeEEnum, LombokType.ALL_ARGS_CONSTRUCTOR);
    addEEnumLiteral(lombokTypeEEnum, LombokType.BUILDER);
    addEEnumLiteral(lombokTypeEEnum, LombokType.DATA);
    addEEnumLiteral(lombokTypeEEnum, LombokType.EQUALS_AND_HASH_CODE);
    addEEnumLiteral(lombokTypeEEnum, LombokType.GETTER);
    addEEnumLiteral(lombokTypeEEnum, LombokType.NO_ARGS_CONSTRUCTOR);
    addEEnumLiteral(lombokTypeEEnum, LombokType.REQUIRED_ARGS_CONSTRUCTOR);
    addEEnumLiteral(lombokTypeEEnum, LombokType.SETTER);
    addEEnumLiteral(lombokTypeEEnum, LombokType.SINGULAR);
    addEEnumLiteral(lombokTypeEEnum, LombokType.SUPER_BUILDER);
    addEEnumLiteral(lombokTypeEEnum, LombokType.TO_STRING);

    initEEnum(builtInTypeEEnum, BuiltInType.class, "BuiltInType");
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.INT);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.LONG);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.INTEGER);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.DOUBLE);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.STRING);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.LOCAL_DATE);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.LOCAL_DATE_TIME);
    addEEnumLiteral(builtInTypeEEnum, BuiltInType.BIG_DECIMAL);

    // Create resource
    createResource(eNS_URI);
  }

} //GenoMatePackageImpl
