/**
 * generated by Xtext 2.38.0
 */
package com.yunzhi.genoMate.impl;

import com.yunzhi.genoMate.Field;
import com.yunzhi.genoMate.GenoMatePackage;
import com.yunzhi.genoMate.MappingRule;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mapping Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.yunzhi.genoMate.impl.MappingRuleImpl#getTargetField <em>Target Field</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.impl.MappingRuleImpl#getSourceField <em>Source Field</em>}</li>
 *   <li>{@link com.yunzhi.genoMate.impl.MappingRuleImpl#getDefault <em>Default</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MappingRuleImpl extends MinimalEObjectImpl.Container implements MappingRule
{
  /**
   * The cached value of the '{@link #getTargetField() <em>Target Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetField()
   * @generated
   * @ordered
   */
  protected Field targetField;

  /**
   * The cached value of the '{@link #getSourceField() <em>Source Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceField()
   * @generated
   * @ordered
   */
  protected Field sourceField;

  /**
   * The default value of the '{@link #getDefault() <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefault()
   * @generated
   * @ordered
   */
  protected static final String DEFAULT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefault() <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefault()
   * @generated
   * @ordered
   */
  protected String default_ = DEFAULT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MappingRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GenoMatePackage.Literals.MAPPING_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field getTargetField()
  {
    if (targetField != null && targetField.eIsProxy())
    {
      InternalEObject oldTargetField = (InternalEObject)targetField;
      targetField = (Field)eResolveProxy(oldTargetField);
      if (targetField != oldTargetField)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GenoMatePackage.MAPPING_RULE__TARGET_FIELD, oldTargetField, targetField));
      }
    }
    return targetField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field basicGetTargetField()
  {
    return targetField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetField(Field newTargetField)
  {
    Field oldTargetField = targetField;
    targetField = newTargetField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenoMatePackage.MAPPING_RULE__TARGET_FIELD, oldTargetField, targetField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field getSourceField()
  {
    if (sourceField != null && sourceField.eIsProxy())
    {
      InternalEObject oldSourceField = (InternalEObject)sourceField;
      sourceField = (Field)eResolveProxy(oldSourceField);
      if (sourceField != oldSourceField)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GenoMatePackage.MAPPING_RULE__SOURCE_FIELD, oldSourceField, sourceField));
      }
    }
    return sourceField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field basicGetSourceField()
  {
    return sourceField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceField(Field newSourceField)
  {
    Field oldSourceField = sourceField;
    sourceField = newSourceField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenoMatePackage.MAPPING_RULE__SOURCE_FIELD, oldSourceField, sourceField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefault()
  {
    return default_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefault(String newDefault)
  {
    String oldDefault = default_;
    default_ = newDefault;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GenoMatePackage.MAPPING_RULE__DEFAULT, oldDefault, default_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GenoMatePackage.MAPPING_RULE__TARGET_FIELD:
        if (resolve) return getTargetField();
        return basicGetTargetField();
      case GenoMatePackage.MAPPING_RULE__SOURCE_FIELD:
        if (resolve) return getSourceField();
        return basicGetSourceField();
      case GenoMatePackage.MAPPING_RULE__DEFAULT:
        return getDefault();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GenoMatePackage.MAPPING_RULE__TARGET_FIELD:
        setTargetField((Field)newValue);
        return;
      case GenoMatePackage.MAPPING_RULE__SOURCE_FIELD:
        setSourceField((Field)newValue);
        return;
      case GenoMatePackage.MAPPING_RULE__DEFAULT:
        setDefault((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GenoMatePackage.MAPPING_RULE__TARGET_FIELD:
        setTargetField((Field)null);
        return;
      case GenoMatePackage.MAPPING_RULE__SOURCE_FIELD:
        setSourceField((Field)null);
        return;
      case GenoMatePackage.MAPPING_RULE__DEFAULT:
        setDefault(DEFAULT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GenoMatePackage.MAPPING_RULE__TARGET_FIELD:
        return targetField != null;
      case GenoMatePackage.MAPPING_RULE__SOURCE_FIELD:
        return sourceField != null;
      case GenoMatePackage.MAPPING_RULE__DEFAULT:
        return DEFAULT_EDEFAULT == null ? default_ != null : !DEFAULT_EDEFAULT.equals(default_);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (default: ");
    result.append(default_);
    result.append(')');
    return result.toString();
  }

} //MappingRuleImpl
