/*
 * generated by Xtext 2.38.0
 */
package com.yunzhi.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.yunzhi.ide.contentassist.antlr.internal.InternalGenoMateParser;
import com.yunzhi.services.GenoMateGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GenoMateParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GenoMateGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GenoMateGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGenerationRuleAccess().getAlternatives(), "rule__GenerationRule__Alternatives");
			builder.put(grammarAccess.getDtoDefinitionAccess().getAlternatives_5_2(), "rule__DtoDefinition__Alternatives_5_2");
			builder.put(grammarAccess.getVoDefinitionAccess().getAlternatives_5_2(), "rule__VoDefinition__Alternatives_5_2");
			builder.put(grammarAccess.getTypeEqualityConditionAccess().getAlternatives_1(), "rule__TypeEqualityCondition__Alternatives_1");
			builder.put(grammarAccess.getMappingAccess().getAlternatives(), "rule__Mapping__Alternatives");
			builder.put(grammarAccess.getModelToVOMappingAccess().getAlternatives_8(), "rule__ModelToVOMapping__Alternatives_8");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getAlternatives_8(), "rule__DTOToModelMapping__Alternatives_8");
			builder.put(grammarAccess.getMappingRuleAccess().getAlternatives_3(), "rule__MappingRule__Alternatives_3");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getArrayTypeAccess().getElementTypeAlternatives_0_0(), "rule__ArrayType__ElementTypeAlternatives_0_0");
			builder.put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
			builder.put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
			builder.put(grammarAccess.getBeanValidationTypeAccess().getAlternatives(), "rule__BeanValidationType__Alternatives");
			builder.put(grammarAccess.getMybatisPlusModelTypeAccess().getAlternatives(), "rule__MybatisPlusModelType__Alternatives");
			builder.put(grammarAccess.getMybatisPlusFieldTypeAccess().getAlternatives(), "rule__MybatisPlusFieldType__Alternatives");
			builder.put(grammarAccess.getJacksonTypeAccess().getAlternatives(), "rule__JacksonType__Alternatives");
			builder.put(grammarAccess.getLombokTypeAccess().getAlternatives(), "rule__LombokType__Alternatives");
			builder.put(grammarAccess.getBuiltInTypeAccess().getAlternatives(), "rule__BuiltInType__Alternatives");
			builder.put(grammarAccess.getGenoMateAccess().getGroup(), "rule__GenoMate__Group__0");
			builder.put(grammarAccess.getGlobalConfigAccess().getGroup(), "rule__GlobalConfig__Group__0");
			builder.put(grammarAccess.getGlobalConfigAccess().getGroup_4(), "rule__GlobalConfig__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getLombokAnnotationAccess().getGroup(), "rule__LombokAnnotation__Group__0");
			builder.put(grammarAccess.getLombokAnnotationAccess().getGroup_2(), "rule__LombokAnnotation__Group_2__0");
			builder.put(grammarAccess.getMybatisPlusModelAnnotationAccess().getGroup(), "rule__MybatisPlusModelAnnotation__Group__0");
			builder.put(grammarAccess.getMybatisPlusModelAnnotationAccess().getGroup_2(), "rule__MybatisPlusModelAnnotation__Group_2__0");
			builder.put(grammarAccess.getMybatisPlusFieldAnnotationAccess().getGroup(), "rule__MybatisPlusFieldAnnotation__Group__0");
			builder.put(grammarAccess.getMybatisPlusFieldAnnotationAccess().getGroup_2(), "rule__MybatisPlusFieldAnnotation__Group_2__0");
			builder.put(grammarAccess.getBeanValidationAnnotationAccess().getGroup(), "rule__BeanValidationAnnotation__Group__0");
			builder.put(grammarAccess.getBeanValidationAnnotationAccess().getGroup_2(), "rule__BeanValidationAnnotation__Group_2__0");
			builder.put(grammarAccess.getJacksonAnnotationAccess().getGroup(), "rule__JacksonAnnotation__Group__0");
			builder.put(grammarAccess.getJacksonAnnotationAccess().getGroup_2(), "rule__JacksonAnnotation__Group_2__0");
			builder.put(grammarAccess.getAnnotationParametersAccess().getGroup(), "rule__AnnotationParameters__Group__0");
			builder.put(grammarAccess.getAnnotationParametersAccess().getGroup_1(), "rule__AnnotationParameters__Group_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getGenerateSectionAccess().getGroup(), "rule__GenerateSection__Group__0");
			builder.put(grammarAccess.getPoRuleAccess().getGroup(), "rule__PoRule__Group__0");
			builder.put(grammarAccess.getPoRuleAccess().getGroup_5(), "rule__PoRule__Group_5__0");
			builder.put(grammarAccess.getPoRuleAccess().getGroup_6(), "rule__PoRule__Group_6__0");
			builder.put(grammarAccess.getPoRuleAccess().getGroup_7(), "rule__PoRule__Group_7__0");
			builder.put(grammarAccess.getPoRuleAccess().getGroup_8(), "rule__PoRule__Group_8__0");
			builder.put(grammarAccess.getDtoRuleAccess().getGroup(), "rule__DtoRule__Group__0");
			builder.put(grammarAccess.getVoRuleAccess().getGroup(), "rule__VoRule__Group__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup(), "rule__DtoDefinition__Group__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup_4(), "rule__DtoDefinition__Group_4__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup_5(), "rule__DtoDefinition__Group_5__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup_5_2_1(), "rule__DtoDefinition__Group_5_2_1__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup_6(), "rule__DtoDefinition__Group_6__0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getGroup_7(), "rule__DtoDefinition__Group_7__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup(), "rule__VoDefinition__Group__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup_4(), "rule__VoDefinition__Group_4__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup_5(), "rule__VoDefinition__Group_5__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup_5_2_1(), "rule__VoDefinition__Group_5_2_1__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup_6(), "rule__VoDefinition__Group_6__0");
			builder.put(grammarAccess.getVoDefinitionAccess().getGroup_7(), "rule__VoDefinition__Group_7__0");
			builder.put(grammarAccess.getFieldAnnotationAccess().getGroup(), "rule__FieldAnnotation__Group__0");
			builder.put(grammarAccess.getFieldValidationBlockAccess().getGroup(), "rule__FieldValidationBlock__Group__0");
			builder.put(grammarAccess.getSingleActionAccess().getGroup(), "rule__SingleAction__Group__0");
			builder.put(grammarAccess.getLocalLoopActionAccess().getGroup(), "rule__LocalLoopAction__Group__0");
			builder.put(grammarAccess.getGlobalActionAccess().getGroup(), "rule__GlobalAction__Group__0");
			builder.put(grammarAccess.getLocalActionAccess().getGroup(), "rule__LocalAction__Group__0");
			builder.put(grammarAccess.getOrTypeConditionAccess().getGroup(), "rule__OrTypeCondition__Group__0");
			builder.put(grammarAccess.getOrTypeConditionAccess().getGroup_1(), "rule__OrTypeCondition__Group_1__0");
			builder.put(grammarAccess.getAndTypeConditionAccess().getGroup(), "rule__AndTypeCondition__Group__0");
			builder.put(grammarAccess.getAndTypeConditionAccess().getGroup_1(), "rule__AndTypeCondition__Group_1__0");
			builder.put(grammarAccess.getTypeEqualityConditionAccess().getGroup(), "rule__TypeEqualityCondition__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getPoAddFieldAccess().getGroup(), "rule__PoAddField__Group__0");
			builder.put(grammarAccess.getPoAddFieldAccess().getGroup_2(), "rule__PoAddField__Group_2__0");
			builder.put(grammarAccess.getDtoAddFieldAccess().getGroup(), "rule__DtoAddField__Group__0");
			builder.put(grammarAccess.getDtoAddFieldAccess().getGroup_2(), "rule__DtoAddField__Group_2__0");
			builder.put(grammarAccess.getVoAddFieldAccess().getGroup(), "rule__VoAddField__Group__0");
			builder.put(grammarAccess.getVoAddFieldAccess().getGroup_2(), "rule__VoAddField__Group_2__0");
			builder.put(grammarAccess.getExclusionsAccess().getGroup(), "rule__Exclusions__Group__0");
			builder.put(grammarAccess.getDtoValidationAccess().getGroup(), "rule__DtoValidation__Group__0");
			builder.put(grammarAccess.getVoJacksonAccess().getGroup(), "rule__VoJackson__Group__0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getGroup(), "rule__PropertyDeclaration__Group__0");
			builder.put(grammarAccess.getDefaultClauseAccess().getGroup(), "rule__DefaultClause__Group__0");
			builder.put(grammarAccess.getModelToVOMappingAccess().getGroup(), "rule__ModelToVOMapping__Group__0");
			builder.put(grammarAccess.getModelToVOMappingAccess().getGroup_8_1(), "rule__ModelToVOMapping__Group_8_1__0");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getGroup(), "rule__DTOToModelMapping__Group__0");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getGroup_8_1(), "rule__DTOToModelMapping__Group_8_1__0");
			builder.put(grammarAccess.getMappingRuleAccess().getGroup(), "rule__MappingRule__Group__0");
			builder.put(grammarAccess.getMappingRuleAccess().getGroup_3_0(), "rule__MappingRule__Group_3_0__0");
			builder.put(grammarAccess.getGenericDataTypeAccess().getGroup(), "rule__GenericDataType__Group__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getGenoMateAccess().getGlobalConfigAssignment_0(), "rule__GenoMate__GlobalConfigAssignment_0");
			builder.put(grammarAccess.getGenoMateAccess().getModelAssignment_1(), "rule__GenoMate__ModelAssignment_1");
			builder.put(grammarAccess.getGenoMateAccess().getGenerateSectionAssignment_2(), "rule__GenoMate__GenerateSectionAssignment_2");
			builder.put(grammarAccess.getGenoMateAccess().getMappingsAssignment_3(), "rule__GenoMate__MappingsAssignment_3");
			builder.put(grammarAccess.getGlobalConfigAccess().getPackageAssignment_3(), "rule__GlobalConfig__PackageAssignment_3");
			builder.put(grammarAccess.getGlobalConfigAccess().getVarDefaultAnnotationsAssignment_4_2(), "rule__GlobalConfig__VarDefaultAnnotationsAssignment_4_2");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getFieldsAssignment_3(), "rule__Model__FieldsAssignment_3");
			builder.put(grammarAccess.getFieldAccess().getTypeAssignment_0(), "rule__Field__TypeAssignment_0");
			builder.put(grammarAccess.getFieldAccess().getNameAssignment_1(), "rule__Field__NameAssignment_1");
			builder.put(grammarAccess.getLombokAnnotationAccess().getNameAssignment_1(), "rule__LombokAnnotation__NameAssignment_1");
			builder.put(grammarAccess.getLombokAnnotationAccess().getParametersAssignment_2_1(), "rule__LombokAnnotation__ParametersAssignment_2_1");
			builder.put(grammarAccess.getMybatisPlusModelAnnotationAccess().getNameAssignment_1(), "rule__MybatisPlusModelAnnotation__NameAssignment_1");
			builder.put(grammarAccess.getMybatisPlusModelAnnotationAccess().getParametersAssignment_2_1(), "rule__MybatisPlusModelAnnotation__ParametersAssignment_2_1");
			builder.put(grammarAccess.getMybatisPlusFieldAnnotationAccess().getNameAssignment_1(), "rule__MybatisPlusFieldAnnotation__NameAssignment_1");
			builder.put(grammarAccess.getMybatisPlusFieldAnnotationAccess().getParametersAssignment_2_1(), "rule__MybatisPlusFieldAnnotation__ParametersAssignment_2_1");
			builder.put(grammarAccess.getBeanValidationAnnotationAccess().getNameAssignment_1(), "rule__BeanValidationAnnotation__NameAssignment_1");
			builder.put(grammarAccess.getBeanValidationAnnotationAccess().getParametersAssignment_2_1(), "rule__BeanValidationAnnotation__ParametersAssignment_2_1");
			builder.put(grammarAccess.getJacksonAnnotationAccess().getNameAssignment_1(), "rule__JacksonAnnotation__NameAssignment_1");
			builder.put(grammarAccess.getJacksonAnnotationAccess().getParametersAssignment_2_1(), "rule__JacksonAnnotation__ParametersAssignment_2_1");
			builder.put(grammarAccess.getAnnotationParametersAccess().getAnnparametersAssignment_0(), "rule__AnnotationParameters__AnnparametersAssignment_0");
			builder.put(grammarAccess.getAnnotationParametersAccess().getParametersAssignment_1_1(), "rule__AnnotationParameters__ParametersAssignment_1_1");
			builder.put(grammarAccess.getParameterAccess().getKeyAssignment_0(), "rule__Parameter__KeyAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getValueAssignment_2(), "rule__Parameter__ValueAssignment_2");
			builder.put(grammarAccess.getGenerateSectionAccess().getRulesAssignment_2(), "rule__GenerateSection__RulesAssignment_2");
			builder.put(grammarAccess.getPoRuleAccess().getModelAssignment_2(), "rule__PoRule__ModelAssignment_2");
			builder.put(grammarAccess.getPoRuleAccess().getSerializableAssignment_4(), "rule__PoRule__SerializableAssignment_4");
			builder.put(grammarAccess.getPoRuleAccess().getLombokAnnotationAssignment_5_1(), "rule__PoRule__LombokAnnotationAssignment_5_1");
			builder.put(grammarAccess.getPoRuleAccess().getMybatisPlusModelAnnotationAssignment_6_1(), "rule__PoRule__MybatisPlusModelAnnotationAssignment_6_1");
			builder.put(grammarAccess.getPoRuleAccess().getFieldAnnsAssignment_7_2(), "rule__PoRule__FieldAnnsAssignment_7_2");
			builder.put(grammarAccess.getPoRuleAccess().getAddFieldAssignment_8_2(), "rule__PoRule__AddFieldAssignment_8_2");
			builder.put(grammarAccess.getDtoRuleAccess().getModelAssignment_2(), "rule__DtoRule__ModelAssignment_2");
			builder.put(grammarAccess.getDtoRuleAccess().getDtosAssignment_4(), "rule__DtoRule__DtosAssignment_4");
			builder.put(grammarAccess.getVoRuleAccess().getModelAssignment_2(), "rule__VoRule__ModelAssignment_2");
			builder.put(grammarAccess.getVoRuleAccess().getVosAssignment_4(), "rule__VoRule__VosAssignment_4");
			builder.put(grammarAccess.getDtoDefinitionAccess().getNameAssignment_1(), "rule__DtoDefinition__NameAssignment_1");
			builder.put(grammarAccess.getDtoDefinitionAccess().getSerializableAssignment_3(), "rule__DtoDefinition__SerializableAssignment_3");
			builder.put(grammarAccess.getDtoDefinitionAccess().getLombokAnnotationAssignment_4_1(), "rule__DtoDefinition__LombokAnnotationAssignment_4_1");
			builder.put(grammarAccess.getDtoDefinitionAccess().getExclusionsAssignment_5_2_0(), "rule__DtoDefinition__ExclusionsAssignment_5_2_0");
			builder.put(grammarAccess.getDtoDefinitionAccess().getExcludeAllAssignment_5_2_1_1(), "rule__DtoDefinition__ExcludeAllAssignment_5_2_1_1");
			builder.put(grammarAccess.getDtoDefinitionAccess().getFieldAnnotationsBlockAssignment_6_2(), "rule__DtoDefinition__FieldAnnotationsBlockAssignment_6_2");
			builder.put(grammarAccess.getDtoDefinitionAccess().getAddFieldAssignment_7_2(), "rule__DtoDefinition__AddFieldAssignment_7_2");
			builder.put(grammarAccess.getVoDefinitionAccess().getNameAssignment_1(), "rule__VoDefinition__NameAssignment_1");
			builder.put(grammarAccess.getVoDefinitionAccess().getSerializableAssignment_3(), "rule__VoDefinition__SerializableAssignment_3");
			builder.put(grammarAccess.getVoDefinitionAccess().getLombokAnnotationAssignment_4_1(), "rule__VoDefinition__LombokAnnotationAssignment_4_1");
			builder.put(grammarAccess.getVoDefinitionAccess().getExclusionsAssignment_5_2_0(), "rule__VoDefinition__ExclusionsAssignment_5_2_0");
			builder.put(grammarAccess.getVoDefinitionAccess().getExcludeAllAssignment_5_2_1_1(), "rule__VoDefinition__ExcludeAllAssignment_5_2_1_1");
			builder.put(grammarAccess.getVoDefinitionAccess().getJacksonsAssignment_6_2(), "rule__VoDefinition__JacksonsAssignment_6_2");
			builder.put(grammarAccess.getVoDefinitionAccess().getAddFieldAssignment_7_2(), "rule__VoDefinition__AddFieldAssignment_7_2");
			builder.put(grammarAccess.getFieldAnnotationAccess().getFieldAssignment_1(), "rule__FieldAnnotation__FieldAssignment_1");
			builder.put(grammarAccess.getFieldAnnotationAccess().getAnnListAssignment_3(), "rule__FieldAnnotation__AnnListAssignment_3");
			builder.put(grammarAccess.getFieldValidationBlockAccess().getActionGlobalAssignment_1(), "rule__FieldValidationBlock__ActionGlobalAssignment_1");
			builder.put(grammarAccess.getFieldValidationBlockAccess().getActionLocalAssignment_2(), "rule__FieldValidationBlock__ActionLocalAssignment_2");
			builder.put(grammarAccess.getFieldValidationBlockAccess().getActionSingleAssignment_3(), "rule__FieldValidationBlock__ActionSingleAssignment_3");
			builder.put(grammarAccess.getSingleActionAccess().getValidationsAssignment_2(), "rule__SingleAction__ValidationsAssignment_2");
			builder.put(grammarAccess.getLocalLoopActionAccess().getVarDeclarationsAssignment_4(), "rule__LocalLoopAction__VarDeclarationsAssignment_4");
			builder.put(grammarAccess.getLocalLoopActionAccess().getActionsAssignment_5(), "rule__LocalLoopAction__ActionsAssignment_5");
			builder.put(grammarAccess.getGlobalActionAccess().getVariableAssignment_3(), "rule__GlobalAction__VariableAssignment_3");
			builder.put(grammarAccess.getLocalActionAccess().getConditionAssignment_2(), "rule__LocalAction__ConditionAssignment_2");
			builder.put(grammarAccess.getLocalActionAccess().getVariableAssignment_6(), "rule__LocalAction__VariableAssignment_6");
			builder.put(grammarAccess.getOrTypeConditionAccess().getLeftAssignment_0(), "rule__OrTypeCondition__LeftAssignment_0");
			builder.put(grammarAccess.getOrTypeConditionAccess().getRightAssignment_1_1(), "rule__OrTypeCondition__RightAssignment_1_1");
			builder.put(grammarAccess.getAndTypeConditionAccess().getLeftAssignment_0(), "rule__AndTypeCondition__LeftAssignment_0");
			builder.put(grammarAccess.getAndTypeConditionAccess().getRightAssignment_1_1(), "rule__AndTypeCondition__RightAssignment_1_1");
			builder.put(grammarAccess.getTypeEqualityConditionAccess().getIsEqualAssignment_1_0(), "rule__TypeEqualityCondition__IsEqualAssignment_1_0");
			builder.put(grammarAccess.getTypeEqualityConditionAccess().getIsNotEqualAssignment_1_1(), "rule__TypeEqualityCondition__IsNotEqualAssignment_1_1");
			builder.put(grammarAccess.getTypeEqualityConditionAccess().getTypeAssignment_2(), "rule__TypeEqualityCondition__TypeAssignment_2");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1(), "rule__VariableDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getAnnotationAssignment_3(), "rule__VariableDeclaration__AnnotationAssignment_3");
			builder.put(grammarAccess.getPoAddFieldAccess().getPropertiesAssignment_1(), "rule__PoAddField__PropertiesAssignment_1");
			builder.put(grammarAccess.getPoAddFieldAccess().getAnnotationListAssignment_2_1(), "rule__PoAddField__AnnotationListAssignment_2_1");
			builder.put(grammarAccess.getDtoAddFieldAccess().getPropertiesAssignment_1(), "rule__DtoAddField__PropertiesAssignment_1");
			builder.put(grammarAccess.getDtoAddFieldAccess().getAnnotationListAssignment_2_1(), "rule__DtoAddField__AnnotationListAssignment_2_1");
			builder.put(grammarAccess.getVoAddFieldAccess().getPropertiesAssignment_1(), "rule__VoAddField__PropertiesAssignment_1");
			builder.put(grammarAccess.getVoAddFieldAccess().getAnnotationListAssignment_2_1(), "rule__VoAddField__AnnotationListAssignment_2_1");
			builder.put(grammarAccess.getExclusionsAccess().getFieldAssignment_1(), "rule__Exclusions__FieldAssignment_1");
			builder.put(grammarAccess.getDtoValidationAccess().getFieldAssignment_1(), "rule__DtoValidation__FieldAssignment_1");
			builder.put(grammarAccess.getDtoValidationAccess().getAnnListAssignment_3(), "rule__DtoValidation__AnnListAssignment_3");
			builder.put(grammarAccess.getVoJacksonAccess().getFieldAssignment_1(), "rule__VoJackson__FieldAssignment_1");
			builder.put(grammarAccess.getVoJacksonAccess().getAnnListAssignment_3(), "rule__VoJackson__AnnListAssignment_3");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getStaticAssignment_0(), "rule__PropertyDeclaration__StaticAssignment_0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getFinalAssignment_1(), "rule__PropertyDeclaration__FinalAssignment_1");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getTypeAssignment_2(), "rule__PropertyDeclaration__TypeAssignment_2");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getNameAssignment_3(), "rule__PropertyDeclaration__NameAssignment_3");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getDefaultClauseAssignment_4(), "rule__PropertyDeclaration__DefaultClauseAssignment_4");
			builder.put(grammarAccess.getModelToVOMappingAccess().getSourceAssignment_3(), "rule__ModelToVOMapping__SourceAssignment_3");
			builder.put(grammarAccess.getModelToVOMappingAccess().getTargetAssignment_6(), "rule__ModelToVOMapping__TargetAssignment_6");
			builder.put(grammarAccess.getModelToVOMappingAccess().getRulesAssignment_8_0(), "rule__ModelToVOMapping__RulesAssignment_8_0");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getSourceAssignment_3(), "rule__DTOToModelMapping__SourceAssignment_3");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getTargetAssignment_6(), "rule__DTOToModelMapping__TargetAssignment_6");
			builder.put(grammarAccess.getDTOToModelMappingAccess().getRulesAssignment_8_0(), "rule__DTOToModelMapping__RulesAssignment_8_0");
			builder.put(grammarAccess.getMappingRuleAccess().getTargetFieldAssignment_1(), "rule__MappingRule__TargetFieldAssignment_1");
			builder.put(grammarAccess.getMappingRuleAccess().getSourceFieldAssignment_3_0_1(), "rule__MappingRule__SourceFieldAssignment_3_0_1");
			builder.put(grammarAccess.getMappingRuleAccess().getDefaultAssignment_3_1(), "rule__MappingRule__DefaultAssignment_3_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getBuiltInTypeAssignment(), "rule__SimpleType__BuiltInTypeAssignment");
			builder.put(grammarAccess.getNormalTypeAccess().getCustomTypeAssignment(), "rule__NormalType__CustomTypeAssignment");
			builder.put(grammarAccess.getGenericDataTypeAccess().getContainerTypeNameAssignment_0(), "rule__GenericDataType__ContainerTypeNameAssignment_0");
			builder.put(grammarAccess.getGenericDataTypeAccess().getContainedTypeNameAssignment_2(), "rule__GenericDataType__ContainedTypeNameAssignment_2");
			builder.put(grammarAccess.getArrayTypeAccess().getElementTypeAssignment_0(), "rule__ArrayType__ElementTypeAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GenoMateGrammarAccess grammarAccess;

	@Override
	protected InternalGenoMateParser createParser() {
		InternalGenoMateParser result = new InternalGenoMateParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GenoMateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GenoMateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
